// Protobuf protocol codec
// TODO: Generate from veil-proto .proto files via prost-build

pub mod proto {
    // Will be generated by build.rs:
    // include!(concat!(env!("OUT_DIR"), "/veil.v1.rs"));
}
