/**
 * Native bridge to veil-ffi (Rust crypto via UniFFI).
 *
 * On Android: Kotlin bindings generated by UniFFI, exposed via TurboModule.
 * On iOS: Swift bindings generated by UniFFI, exposed via TurboModule.
 *
 * This module provides a JS interface that mirrors the FFI surface.
 * Until the native module is built, we use a mock implementation.
 */
import { NativeModules, Platform } from "react-native";

interface VeilCryptoNative {
  generateMnemonic(): Promise<string>;
  validateMnemonic(mnemonic: string): Promise<boolean>;
  createIdentity(mnemonic: string): Promise<string>; // returns hex identity key
  getIdentityKey(): Promise<string>;
  getSigningKey(): Promise<string>;
  sign(message: string): Promise<string>; // hex signature
  verify(publicKey: string, message: string, signature: string): Promise<boolean>;
  generateFingerprint(keyA: string, keyB: string): Promise<{ emoji: string; hex: string }>;
  aeadEncrypt(keyHex: string, plaintext: string): Promise<{ ciphertext: string; nonce: string }>;
  aeadDecrypt(keyHex: string, ciphertext: string, nonce: string): Promise<string>;
}

const NativeCrypto: VeilCryptoNative | undefined =
  NativeModules.VeilCrypto as VeilCryptoNative | undefined;

// TODO: Replace mock with real native module after UniFFI integration
const MockCrypto: VeilCryptoNative = {
  async generateMnemonic() {
    return "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about";
  },
  async validateMnemonic(_m: string) {
    return _m.split(" ").length >= 12;
  },
  async createIdentity(_m: string) {
    return "0".repeat(64);
  },
  async getIdentityKey() {
    return "0".repeat(64);
  },
  async getSigningKey() {
    return "0".repeat(64);
  },
  async sign(_msg: string) {
    return "0".repeat(128);
  },
  async verify(_pk: string, _msg: string, _sig: string) {
    return true;
  },
  async generateFingerprint(_a: string, _b: string) {
    return { emoji: "🔒🔑", hex: "0".repeat(64) };
  },
  async aeadEncrypt(_k: string, _pt: string) {
    return { ciphertext: "", nonce: "" };
  },
  async aeadDecrypt(_k: string, _ct: string, _n: string) {
    return "";
  },
};

const VeilCrypto: VeilCryptoNative =
  Platform.OS !== "web" && NativeCrypto
    ? NativeCrypto
    : (() => {
        if (__DEV__) {
          console.warn("[VeilCrypto] Using MOCK crypto — NOT safe for production");
          return MockCrypto;
        }
        throw new Error(
          "VeilCrypto native module is not available. " +
            "Ensure the UniFFI bindings are linked.",
        );
      })();

export default VeilCrypto;
