/**
 * Native bridge to veil-ffi (Rust crypto via UniFFI).
 *
 * On Android: Kotlin bindings generated by UniFFI, exposed via TurboModule.
 * On iOS: Swift bindings generated by UniFFI, exposed via TurboModule.
 *
 * This module provides a JS interface that mirrors the FFI surface.
 * Missing native code is always a hard failure. Cryptographic mocks belong in
 * individual tests, never in the application runtime.
 */
import { NativeModules, Platform } from "react-native";

interface VeilCryptoNative {
  generateMnemonic(): Promise<string>;
  validateMnemonic(mnemonic: string): Promise<boolean>;
  hasIdentity(): Promise<boolean>;
  setSensitiveScreen(enabled: boolean): Promise<boolean>;
  createIdentity(mnemonic: string): Promise<string>; // returns hex identity key
  getIdentityKey(): Promise<string>;
}

const NativeCrypto: VeilCryptoNative | undefined =
  NativeModules.VeilCrypto as VeilCryptoNative | undefined;

const unavailable = () =>
  Promise.reject(
    new Error(
      `VeilCrypto native module is unavailable on ${Platform.OS}. ` +
        "Use a native Veil build with the Rust library linked.",
    ),
  );

const UnavailableCrypto: VeilCryptoNative = new Proxy({} as VeilCryptoNative, {
  get: () => unavailable,
});

const VeilCrypto: VeilCryptoNative =
  Platform.OS !== "web" && NativeCrypto ? NativeCrypto : UnavailableCrypto;

export default VeilCrypto;
