// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: veil/v1/auth.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Machine-readable authentication outcomes. REGISTRATION_CLOSED and
// INVITE_INVALID are emitted only after account-key proof succeeds, avoiding
// an unauthenticated account/invite oracle. Invalid, expired, and reused
// invites intentionally share one indistinguishable result.
type AuthFailureReason int32

const (
	AuthFailureReason_AUTH_FAILURE_REASON_UNSPECIFIED           AuthFailureReason = 0
	AuthFailureReason_AUTH_FAILURE_REASON_AUTHENTICATION_FAILED AuthFailureReason = 1
	AuthFailureReason_AUTH_FAILURE_REASON_REGISTRATION_CLOSED   AuthFailureReason = 2
	AuthFailureReason_AUTH_FAILURE_REASON_INVITE_INVALID        AuthFailureReason = 3
)

// Enum value maps for AuthFailureReason.
var (
	AuthFailureReason_name = map[int32]string{
		0: "AUTH_FAILURE_REASON_UNSPECIFIED",
		1: "AUTH_FAILURE_REASON_AUTHENTICATION_FAILED",
		2: "AUTH_FAILURE_REASON_REGISTRATION_CLOSED",
		3: "AUTH_FAILURE_REASON_INVITE_INVALID",
	}
	AuthFailureReason_value = map[string]int32{
		"AUTH_FAILURE_REASON_UNSPECIFIED":           0,
		"AUTH_FAILURE_REASON_AUTHENTICATION_FAILED": 1,
		"AUTH_FAILURE_REASON_REGISTRATION_CLOSED":   2,
		"AUTH_FAILURE_REASON_INVITE_INVALID":        3,
	}
)

func (x AuthFailureReason) Enum() *AuthFailureReason {
	p := new(AuthFailureReason)
	*p = x
	return p
}

func (x AuthFailureReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthFailureReason) Descriptor() protoreflect.EnumDescriptor {
	return file_veil_v1_auth_proto_enumTypes[0].Descriptor()
}

func (AuthFailureReason) Type() protoreflect.EnumType {
	return &file_veil_v1_auth_proto_enumTypes[0]
}

func (x AuthFailureReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthFailureReason.Descriptor instead.
func (AuthFailureReason) EnumDescriptor() ([]byte, []int) {
	return file_veil_v1_auth_proto_rawDescGZIP(), []int{0}
}

// Bit values carried in DeviceBindingV1.capabilities. Values may be ORed.
type DeviceCapability int32

const (
	DeviceCapability_DEVICE_CAPABILITY_UNSPECIFIED    DeviceCapability = 0
	DeviceCapability_DEVICE_CAPABILITY_SENDER_KEY_V5  DeviceCapability = 1
	DeviceCapability_DEVICE_CAPABILITY_SEALED_SKDM_V3 DeviceCapability = 2
)

// Enum value maps for DeviceCapability.
var (
	DeviceCapability_name = map[int32]string{
		0: "DEVICE_CAPABILITY_UNSPECIFIED",
		1: "DEVICE_CAPABILITY_SENDER_KEY_V5",
		2: "DEVICE_CAPABILITY_SEALED_SKDM_V3",
	}
	DeviceCapability_value = map[string]int32{
		"DEVICE_CAPABILITY_UNSPECIFIED":    0,
		"DEVICE_CAPABILITY_SENDER_KEY_V5":  1,
		"DEVICE_CAPABILITY_SEALED_SKDM_V3": 2,
	}
)

func (x DeviceCapability) Enum() *DeviceCapability {
	p := new(DeviceCapability)
	*p = x
	return p
}

func (x DeviceCapability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceCapability) Descriptor() protoreflect.EnumDescriptor {
	return file_veil_v1_auth_proto_enumTypes[1].Descriptor()
}

func (DeviceCapability) Type() protoreflect.EnumType {
	return &file_veil_v1_auth_proto_enumTypes[1]
}

func (x DeviceCapability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceCapability.Descriptor instead.
func (DeviceCapability) EnumDescriptor() ([]byte, []int) {
	return file_veil_v1_auth_proto_rawDescGZIP(), []int{1}
}

type DeviceBindingStatus int32

const (
	DeviceBindingStatus_DEVICE_BINDING_STATUS_UNSPECIFIED DeviceBindingStatus = 0
	DeviceBindingStatus_DEVICE_BINDING_STATUS_ACTIVE      DeviceBindingStatus = 1
	DeviceBindingStatus_DEVICE_BINDING_STATUS_EXCLUDED    DeviceBindingStatus = 2
	DeviceBindingStatus_DEVICE_BINDING_STATUS_REVOKED     DeviceBindingStatus = 3
	// Response-only transitional state. It is never a valid signed binding.
	DeviceBindingStatus_DEVICE_BINDING_STATUS_LEGACY_UNBOUND DeviceBindingStatus = 4
)

// Enum value maps for DeviceBindingStatus.
var (
	DeviceBindingStatus_name = map[int32]string{
		0: "DEVICE_BINDING_STATUS_UNSPECIFIED",
		1: "DEVICE_BINDING_STATUS_ACTIVE",
		2: "DEVICE_BINDING_STATUS_EXCLUDED",
		3: "DEVICE_BINDING_STATUS_REVOKED",
		4: "DEVICE_BINDING_STATUS_LEGACY_UNBOUND",
	}
	DeviceBindingStatus_value = map[string]int32{
		"DEVICE_BINDING_STATUS_UNSPECIFIED":    0,
		"DEVICE_BINDING_STATUS_ACTIVE":         1,
		"DEVICE_BINDING_STATUS_EXCLUDED":       2,
		"DEVICE_BINDING_STATUS_REVOKED":        3,
		"DEVICE_BINDING_STATUS_LEGACY_UNBOUND": 4,
	}
)

func (x DeviceBindingStatus) Enum() *DeviceBindingStatus {
	p := new(DeviceBindingStatus)
	*p = x
	return p
}

func (x DeviceBindingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceBindingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_veil_v1_auth_proto_enumTypes[2].Descriptor()
}

func (DeviceBindingStatus) Type() protoreflect.EnumType {
	return &file_veil_v1_auth_proto_enumTypes[2]
}

func (x DeviceBindingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceBindingStatus.Descriptor instead.
func (DeviceBindingStatus) EnumDescriptor() ([]byte, []int) {
	return file_veil_v1_auth_proto_rawDescGZIP(), []int{2}
}

// Dedicated WebSocket auth v3 wire foundation. Appended after every legacy
// declaration so generated descriptor indexes remain stable. The current /ws
// runtime stays on legacy AuthChallenge/AuthResponse/AuthResult and does not
// emit or accept these messages before the separately reviewed activation.
type WsRegistrationIntentV3 int32

const (
	WsRegistrationIntentV3_WS_REGISTRATION_INTENT_V3_UNSPECIFIED WsRegistrationIntentV3 = 0
	WsRegistrationIntentV3_WS_REGISTRATION_INTENT_V3_EXISTING    WsRegistrationIntentV3 = 1
	WsRegistrationIntentV3_WS_REGISTRATION_INTENT_V3_OPEN        WsRegistrationIntentV3 = 2
	WsRegistrationIntentV3_WS_REGISTRATION_INTENT_V3_PASS        WsRegistrationIntentV3 = 3
)

// Enum value maps for WsRegistrationIntentV3.
var (
	WsRegistrationIntentV3_name = map[int32]string{
		0: "WS_REGISTRATION_INTENT_V3_UNSPECIFIED",
		1: "WS_REGISTRATION_INTENT_V3_EXISTING",
		2: "WS_REGISTRATION_INTENT_V3_OPEN",
		3: "WS_REGISTRATION_INTENT_V3_PASS",
	}
	WsRegistrationIntentV3_value = map[string]int32{
		"WS_REGISTRATION_INTENT_V3_UNSPECIFIED": 0,
		"WS_REGISTRATION_INTENT_V3_EXISTING":    1,
		"WS_REGISTRATION_INTENT_V3_OPEN":        2,
		"WS_REGISTRATION_INTENT_V3_PASS":        3,
	}
)

func (x WsRegistrationIntentV3) Enum() *WsRegistrationIntentV3 {
	p := new(WsRegistrationIntentV3)
	*p = x
	return p
}

func (x WsRegistrationIntentV3) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WsRegistrationIntentV3) Descriptor() protoreflect.EnumDescriptor {
	return file_veil_v1_auth_proto_enumTypes[3].Descriptor()
}

func (WsRegistrationIntentV3) Type() protoreflect.EnumType {
	return &file_veil_v1_auth_proto_enumTypes[3]
}

func (x WsRegistrationIntentV3) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WsRegistrationIntentV3.Descriptor instead.
func (WsRegistrationIntentV3) EnumDescriptor() ([]byte, []int) {
	return file_veil_v1_auth_proto_rawDescGZIP(), []int{3}
}

type WsAuthFailureReasonV3 int32

const (
	WsAuthFailureReasonV3_WS_AUTH_FAILURE_REASON_V3_UNSPECIFIED              WsAuthFailureReasonV3 = 0
	WsAuthFailureReasonV3_WS_AUTH_FAILURE_REASON_V3_AUTHENTICATION_FAILED    WsAuthFailureReasonV3 = 1
	WsAuthFailureReasonV3_WS_AUTH_FAILURE_REASON_V3_REGISTRATION_CLOSED      WsAuthFailureReasonV3 = 2
	WsAuthFailureReasonV3_WS_AUTH_FAILURE_REASON_V3_NODE_ACCESS_PASS_INVALID WsAuthFailureReasonV3 = 3
)

// Enum value maps for WsAuthFailureReasonV3.
var (
	WsAuthFailureReasonV3_name = map[int32]string{
		0: "WS_AUTH_FAILURE_REASON_V3_UNSPECIFIED",
		1: "WS_AUTH_FAILURE_REASON_V3_AUTHENTICATION_FAILED",
		2: "WS_AUTH_FAILURE_REASON_V3_REGISTRATION_CLOSED",
		3: "WS_AUTH_FAILURE_REASON_V3_NODE_ACCESS_PASS_INVALID",
	}
	WsAuthFailureReasonV3_value = map[string]int32{
		"WS_AUTH_FAILURE_REASON_V3_UNSPECIFIED":              0,
		"WS_AUTH_FAILURE_REASON_V3_AUTHENTICATION_FAILED":    1,
		"WS_AUTH_FAILURE_REASON_V3_REGISTRATION_CLOSED":      2,
		"WS_AUTH_FAILURE_REASON_V3_NODE_ACCESS_PASS_INVALID": 3,
	}
)

func (x WsAuthFailureReasonV3) Enum() *WsAuthFailureReasonV3 {
	p := new(WsAuthFailureReasonV3)
	*p = x
	return p
}

func (x WsAuthFailureReasonV3) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WsAuthFailureReasonV3) Descriptor() protoreflect.EnumDescriptor {
	return file_veil_v1_auth_proto_enumTypes[4].Descriptor()
}

func (WsAuthFailureReasonV3) Type() protoreflect.EnumType {
	return &file_veil_v1_auth_proto_enumTypes[4]
}

func (x WsAuthFailureReasonV3) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WsAuthFailureReasonV3.Descriptor instead.
func (WsAuthFailureReasonV3) EnumDescriptor() ([]byte, []int) {
	return file_veil_v1_auth_proto_rawDescGZIP(), []int{4}
}

// Сервер отправляет challenge при подключении
type AuthChallenge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Challenge     []byte                 `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"` // 32 bytes random
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthChallenge) Reset() {
	*x = AuthChallenge{}
	mi := &file_veil_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthChallenge) ProtoMessage() {}

func (x *AuthChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthChallenge.ProtoReflect.Descriptor instead.
func (*AuthChallenge) Descriptor() ([]byte, []int) {
	return file_veil_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthChallenge) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

// Клиент подписывает challenge и отправляет identity
type AuthResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IdentityKey     []byte                 `protobuf:"bytes,1,opt,name=identity_key,json=identityKey,proto3" json:"identity_key,omitempty"`             // X25519 public key (32 bytes)
	SigningKey      []byte                 `protobuf:"bytes,2,opt,name=signing_key,json=signingKey,proto3" json:"signing_key,omitempty"`                // Ed25519 public key (32 bytes)
	Signature       []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`                                    // Ed25519 signature of challenge
	DeviceId        []byte                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                      // Unique device ID (16 bytes UUID)
	DeviceName      string                 `protobuf:"bytes,5,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`                // Human-readable: "Pixel 9", "MacBook Pro"
	ClientVersion   string                 `protobuf:"bytes,6,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`       // "veil-desktop/1.0.0"
	DeviceBinding   *DeviceBindingV1       `protobuf:"bytes,7,opt,name=device_binding,json=deviceBinding,proto3" json:"device_binding,omitempty"`       // Present only for cryptographic per-device auth.
	DeviceSignature []byte                 `protobuf:"bytes,8,opt,name=device_signature,json=deviceSignature,proto3" json:"device_signature,omitempty"` // Ed25519 signature over veil-device-auth-v1 preimage.
	// Optional 256-bit Node Access invite. A first-time identity presents it
	// inside the already-established TLS WebSocket after proving possession of
	// its account keys. Existing identities never need an invite.
	NodeAccessInvite []byte `protobuf:"bytes,9,opt,name=node_access_invite,json=nodeAccessInvite,proto3" json:"node_access_invite,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_veil_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_veil_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthResponse) GetIdentityKey() []byte {
	if x != nil {
		return x.IdentityKey
	}
	return nil
}

func (x *AuthResponse) GetSigningKey() []byte {
	if x != nil {
		return x.SigningKey
	}
	return nil
}

func (x *AuthResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AuthResponse) GetDeviceId() []byte {
	if x != nil {
		return x.DeviceId
	}
	return nil
}

func (x *AuthResponse) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *AuthResponse) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *AuthResponse) GetDeviceBinding() *DeviceBindingV1 {
	if x != nil {
		return x.DeviceBinding
	}
	return nil
}

func (x *AuthResponse) GetDeviceSignature() []byte {
	if x != nil {
		return x.DeviceSignature
	}
	return nil
}

func (x *AuthResponse) GetNodeAccessInvite() []byte {
	if x != nil {
		return x.NodeAccessInvite
	}
	return nil
}

// Результат аутентификации
type AuthResult struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Success              bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UserId               *string                `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	ErrorMessage         *string                `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	PerDeviceSecure      bool                   `protobuf:"varint,4,opt,name=per_device_secure,json=perDeviceSecure,proto3" json:"per_device_secure,omitempty"`
	DeviceBindingVersion uint64                 `protobuf:"varint,5,opt,name=device_binding_version,json=deviceBindingVersion,proto3" json:"device_binding_version,omitempty"`
	DeviceBindingStatus  DeviceBindingStatus    `protobuf:"varint,6,opt,name=device_binding_status,json=deviceBindingStatus,proto3,enum=veil.v1.DeviceBindingStatus" json:"device_binding_status,omitempty"`
	FailureReason        AuthFailureReason      `protobuf:"varint,7,opt,name=failure_reason,json=failureReason,proto3,enum=veil.v1.AuthFailureReason" json:"failure_reason,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AuthResult) Reset() {
	*x = AuthResult{}
	mi := &file_veil_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResult) ProtoMessage() {}

func (x *AuthResult) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResult.ProtoReflect.Descriptor instead.
func (*AuthResult) Descriptor() ([]byte, []int) {
	return file_veil_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AuthResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthResult) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *AuthResult) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *AuthResult) GetPerDeviceSecure() bool {
	if x != nil {
		return x.PerDeviceSecure
	}
	return false
}

func (x *AuthResult) GetDeviceBindingVersion() uint64 {
	if x != nil {
		return x.DeviceBindingVersion
	}
	return 0
}

func (x *AuthResult) GetDeviceBindingStatus() DeviceBindingStatus {
	if x != nil {
		return x.DeviceBindingStatus
	}
	return DeviceBindingStatus_DEVICE_BINDING_STATUS_UNSPECIFIED
}

func (x *AuthResult) GetFailureReason() AuthFailureReason {
	if x != nil {
		return x.FailureReason
	}
	return AuthFailureReason_AUTH_FAILURE_REASON_UNSPECIFIED
}

// Account-authorized immutable version of one cryptographic device binding.
// device_id is the existing stable 16-byte device identifier. Key replacement
// requires a new device_id; later versions may change only capabilities/status.
type DeviceBindingV1 struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DeviceId          []byte                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                              // 16 bytes
	DeviceIdentityKey []byte                 `protobuf:"bytes,2,opt,name=device_identity_key,json=deviceIdentityKey,proto3" json:"device_identity_key,omitempty"` // X25519 public key, 32 bytes
	DeviceSigningKey  []byte                 `protobuf:"bytes,3,opt,name=device_signing_key,json=deviceSigningKey,proto3" json:"device_signing_key,omitempty"`    // Ed25519 public key, 32 bytes
	Version           uint64                 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`                                               // 1..2^63-1; advances exactly by one
	Capabilities      uint64                 `protobuf:"varint,5,opt,name=capabilities,proto3" json:"capabilities,omitempty"`                                     // DeviceCapability mask; bit 63 is reserved
	Status            DeviceBindingStatus    `protobuf:"varint,6,opt,name=status,proto3,enum=veil.v1.DeviceBindingStatus" json:"status,omitempty"`
	AccountSignature  []byte                 `protobuf:"bytes,7,opt,name=account_signature,json=accountSignature,proto3" json:"account_signature,omitempty"` // Account Ed25519 signature, 64 bytes
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeviceBindingV1) Reset() {
	*x = DeviceBindingV1{}
	mi := &file_veil_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceBindingV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceBindingV1) ProtoMessage() {}

func (x *DeviceBindingV1) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceBindingV1.ProtoReflect.Descriptor instead.
func (*DeviceBindingV1) Descriptor() ([]byte, []int) {
	return file_veil_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceBindingV1) GetDeviceId() []byte {
	if x != nil {
		return x.DeviceId
	}
	return nil
}

func (x *DeviceBindingV1) GetDeviceIdentityKey() []byte {
	if x != nil {
		return x.DeviceIdentityKey
	}
	return nil
}

func (x *DeviceBindingV1) GetDeviceSigningKey() []byte {
	if x != nil {
		return x.DeviceSigningKey
	}
	return nil
}

func (x *DeviceBindingV1) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DeviceBindingV1) GetCapabilities() uint64 {
	if x != nil {
		return x.Capabilities
	}
	return 0
}

func (x *DeviceBindingV1) GetStatus() DeviceBindingStatus {
	if x != nil {
		return x.Status
	}
	return DeviceBindingStatus_DEVICE_BINDING_STATUS_UNSPECIFIED
}

func (x *DeviceBindingV1) GetAccountSignature() []byte {
	if x != nil {
		return x.AccountSignature
	}
	return nil
}

type DeviceDirectoryEntry struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username           string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	DeviceId           []byte                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Binding            *DeviceBindingV1       `protobuf:"bytes,4,opt,name=binding,proto3,oneof" json:"binding,omitempty"`
	Eligible           bool                   `protobuf:"varint,5,opt,name=eligible,proto3" json:"eligible,omitempty"`
	ExclusionReason    *string                `protobuf:"bytes,6,opt,name=exclusion_reason,json=exclusionReason,proto3,oneof" json:"exclusion_reason,omitempty"`
	AccountIdentityKey []byte                 `protobuf:"bytes,7,opt,name=account_identity_key,json=accountIdentityKey,proto3" json:"account_identity_key,omitempty"` // Account X25519 public key, 32 bytes
	AccountSigningKey  []byte                 `protobuf:"bytes,8,opt,name=account_signing_key,json=accountSigningKey,proto3" json:"account_signing_key,omitempty"`    // Account Ed25519 public key, 32 bytes
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DeviceDirectoryEntry) Reset() {
	*x = DeviceDirectoryEntry{}
	mi := &file_veil_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceDirectoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceDirectoryEntry) ProtoMessage() {}

func (x *DeviceDirectoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceDirectoryEntry.ProtoReflect.Descriptor instead.
func (*DeviceDirectoryEntry) Descriptor() ([]byte, []int) {
	return file_veil_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceDirectoryEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeviceDirectoryEntry) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DeviceDirectoryEntry) GetDeviceId() []byte {
	if x != nil {
		return x.DeviceId
	}
	return nil
}

func (x *DeviceDirectoryEntry) GetBinding() *DeviceBindingV1 {
	if x != nil {
		return x.Binding
	}
	return nil
}

func (x *DeviceDirectoryEntry) GetEligible() bool {
	if x != nil {
		return x.Eligible
	}
	return false
}

func (x *DeviceDirectoryEntry) GetExclusionReason() string {
	if x != nil && x.ExclusionReason != nil {
		return *x.ExclusionReason
	}
	return ""
}

func (x *DeviceDirectoryEntry) GetAccountIdentityKey() []byte {
	if x != nil {
		return x.AccountIdentityKey
	}
	return nil
}

func (x *DeviceDirectoryEntry) GetAccountSigningKey() []byte {
	if x != nil {
		return x.AccountSigningKey
	}
	return nil
}

type ConversationDeviceDirectory struct {
	state                protoimpl.MessageState  `protogen:"open.v1"`
	ConversationId       string                  `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	RosterVersion        uint64                  `protobuf:"varint,2,opt,name=roster_version,json=rosterVersion,proto3" json:"roster_version,omitempty"`
	RosterCommitment     []byte                  `protobuf:"bytes,3,opt,name=roster_commitment,json=rosterCommitment,proto3" json:"roster_commitment,omitempty"`
	Ready                bool                    `protobuf:"varint,4,opt,name=ready,proto3" json:"ready,omitempty"`
	Reason               *string                 `protobuf:"bytes,5,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	RequiredCapabilities uint64                  `protobuf:"varint,6,opt,name=required_capabilities,json=requiredCapabilities,proto3" json:"required_capabilities,omitempty"`
	MemberUserIds        []string                `protobuf:"bytes,7,rep,name=member_user_ids,json=memberUserIds,proto3" json:"member_user_ids,omitempty"`
	Devices              []*DeviceDirectoryEntry `protobuf:"bytes,8,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ConversationDeviceDirectory) Reset() {
	*x = ConversationDeviceDirectory{}
	mi := &file_veil_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationDeviceDirectory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationDeviceDirectory) ProtoMessage() {}

func (x *ConversationDeviceDirectory) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationDeviceDirectory.ProtoReflect.Descriptor instead.
func (*ConversationDeviceDirectory) Descriptor() ([]byte, []int) {
	return file_veil_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *ConversationDeviceDirectory) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationDeviceDirectory) GetRosterVersion() uint64 {
	if x != nil {
		return x.RosterVersion
	}
	return 0
}

func (x *ConversationDeviceDirectory) GetRosterCommitment() []byte {
	if x != nil {
		return x.RosterCommitment
	}
	return nil
}

func (x *ConversationDeviceDirectory) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *ConversationDeviceDirectory) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *ConversationDeviceDirectory) GetRequiredCapabilities() uint64 {
	if x != nil {
		return x.RequiredCapabilities
	}
	return 0
}

func (x *ConversationDeviceDirectory) GetMemberUserIds() []string {
	if x != nil {
		return x.MemberUserIds
	}
	return nil
}

func (x *ConversationDeviceDirectory) GetDevices() []*DeviceDirectoryEntry {
	if x != nil {
		return x.Devices
	}
	return nil
}

// Регистрация нового устройства (link existing account)
type RegisterDevice struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	IdentityKey []byte                 `protobuf:"bytes,1,opt,name=identity_key,json=identityKey,proto3" json:"identity_key,omitempty"`
	SigningKey  []byte                 `protobuf:"bytes,2,opt,name=signing_key,json=signingKey,proto3" json:"signing_key,omitempty"`
	DeviceId    []byte                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceName  string                 `protobuf:"bytes,4,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Для привязки к существующему аккаунту:
	LinkSignature []byte `protobuf:"bytes,5,opt,name=link_signature,json=linkSignature,proto3,oneof" json:"link_signature,omitempty"` // Подпись от master device
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDevice) Reset() {
	*x = RegisterDevice{}
	mi := &file_veil_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDevice) ProtoMessage() {}

func (x *RegisterDevice) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDevice.ProtoReflect.Descriptor instead.
func (*RegisterDevice) Descriptor() ([]byte, []int) {
	return file_veil_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterDevice) GetIdentityKey() []byte {
	if x != nil {
		return x.IdentityKey
	}
	return nil
}

func (x *RegisterDevice) GetSigningKey() []byte {
	if x != nil {
		return x.SigningKey
	}
	return nil
}

func (x *RegisterDevice) GetDeviceId() []byte {
	if x != nil {
		return x.DeviceId
	}
	return nil
}

func (x *RegisterDevice) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *RegisterDevice) GetLinkSignature() []byte {
	if x != nil {
		return x.LinkSignature
	}
	return nil
}

type AuthChallengeV3 struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion     uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`              // Must be exactly 3 at the future runtime boundary.
	ServerEphemeral     []byte                 `protobuf:"bytes,2,opt,name=server_ephemeral,json=serverEphemeral,proto3" json:"server_ephemeral,omitempty"`               // X25519 public key, exactly 32 bytes.
	CanonicalNodeOrigin string                 `protobuf:"bytes,3,opt,name=canonical_node_origin,json=canonicalNodeOrigin,proto3" json:"canonical_node_origin,omitempty"` // Exact configured canonical Node origin.
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AuthChallengeV3) Reset() {
	*x = AuthChallengeV3{}
	mi := &file_veil_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthChallengeV3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthChallengeV3) ProtoMessage() {}

func (x *AuthChallengeV3) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthChallengeV3.ProtoReflect.Descriptor instead.
func (*AuthChallengeV3) Descriptor() ([]byte, []int) {
	return file_veil_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *AuthChallengeV3) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *AuthChallengeV3) GetServerEphemeral() []byte {
	if x != nil {
		return x.ServerEphemeral
	}
	return nil
}

func (x *AuthChallengeV3) GetCanonicalNodeOrigin() string {
	if x != nil {
		return x.CanonicalNodeOrigin
	}
	return ""
}

type AuthResponseV3 struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion       uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`                    // Must be exactly 3.
	IdentityKey           []byte                 `protobuf:"bytes,2,opt,name=identity_key,json=identityKey,proto3" json:"identity_key,omitempty"`                                 // Account X25519 public key, exactly 32 bytes.
	SigningKey            []byte                 `protobuf:"bytes,3,opt,name=signing_key,json=signingKey,proto3" json:"signing_key,omitempty"`                                    // Account Ed25519 public key, exactly 32 bytes.
	AccountProofSignature []byte                 `protobuf:"bytes,4,opt,name=account_proof_signature,json=accountProofSignature,proto3" json:"account_proof_signature,omitempty"` // Ed25519 signature over the v3 account proof.
	DeviceId              []byte                 `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                                          // Stable device identifier, exactly 16 bytes.
	DeviceName            string                 `protobuf:"bytes,6,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	ClientVersion         string                 `protobuf:"bytes,7,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	DeviceBinding         *DeviceBindingV1       `protobuf:"bytes,8,opt,name=device_binding,json=deviceBinding,proto3" json:"device_binding,omitempty"`                        // Required and strictly verified before commitment use.
	DeviceProofSignature  []byte                 `protobuf:"bytes,9,opt,name=device_proof_signature,json=deviceProofSignature,proto3" json:"device_proof_signature,omitempty"` // Ed25519 signature over the chained v3 device proof.
	RegistrationIntent    WsRegistrationIntentV3 `protobuf:"varint,10,opt,name=registration_intent,json=registrationIntent,proto3,enum=veil.v1.WsRegistrationIntentV3" json:"registration_intent,omitempty"`
	// Raw 32-byte bearer only for PASS intent. The future runtime must clear
	// decoded copies promptly and derive the signed origin-scoped commitment.
	NodeAccessPass []byte `protobuf:"bytes,11,opt,name=node_access_pass,json=nodeAccessPass,proto3" json:"node_access_pass,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthResponseV3) Reset() {
	*x = AuthResponseV3{}
	mi := &file_veil_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponseV3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponseV3) ProtoMessage() {}

func (x *AuthResponseV3) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponseV3.ProtoReflect.Descriptor instead.
func (*AuthResponseV3) Descriptor() ([]byte, []int) {
	return file_veil_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *AuthResponseV3) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *AuthResponseV3) GetIdentityKey() []byte {
	if x != nil {
		return x.IdentityKey
	}
	return nil
}

func (x *AuthResponseV3) GetSigningKey() []byte {
	if x != nil {
		return x.SigningKey
	}
	return nil
}

func (x *AuthResponseV3) GetAccountProofSignature() []byte {
	if x != nil {
		return x.AccountProofSignature
	}
	return nil
}

func (x *AuthResponseV3) GetDeviceId() []byte {
	if x != nil {
		return x.DeviceId
	}
	return nil
}

func (x *AuthResponseV3) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *AuthResponseV3) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *AuthResponseV3) GetDeviceBinding() *DeviceBindingV1 {
	if x != nil {
		return x.DeviceBinding
	}
	return nil
}

func (x *AuthResponseV3) GetDeviceProofSignature() []byte {
	if x != nil {
		return x.DeviceProofSignature
	}
	return nil
}

func (x *AuthResponseV3) GetRegistrationIntent() WsRegistrationIntentV3 {
	if x != nil {
		return x.RegistrationIntent
	}
	return WsRegistrationIntentV3_WS_REGISTRATION_INTENT_V3_UNSPECIFIED
}

func (x *AuthResponseV3) GetNodeAccessPass() []byte {
	if x != nil {
		return x.NodeAccessPass
	}
	return nil
}

type AuthResultV3 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Canonical success has user_id present, per_device_secure=true, a positive
	// active binding version/status, failure_reason=UNSPECIFIED, and no
	// error_message. Canonical failure has no user_id, per_device_secure=false,
	// binding version 0/status UNSPECIFIED, and one known non-zero reason;
	// error_message is optional untrusted diagnostic text only.
	// REGISTRATION_CLOSED is valid only for the signed OPEN intent and
	// NODE_ACCESS_PASS_INVALID only for the signed PASS intent.
	ProtocolVersion      uint32                `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // Must be exactly 3.
	Success              bool                  `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	UserId               *string               `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	ErrorMessage         *string               `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	PerDeviceSecure      bool                  `protobuf:"varint,5,opt,name=per_device_secure,json=perDeviceSecure,proto3" json:"per_device_secure,omitempty"`
	DeviceBindingVersion uint64                `protobuf:"varint,6,opt,name=device_binding_version,json=deviceBindingVersion,proto3" json:"device_binding_version,omitempty"`
	DeviceBindingStatus  DeviceBindingStatus   `protobuf:"varint,7,opt,name=device_binding_status,json=deviceBindingStatus,proto3,enum=veil.v1.DeviceBindingStatus" json:"device_binding_status,omitempty"`
	FailureReason        WsAuthFailureReasonV3 `protobuf:"varint,8,opt,name=failure_reason,json=failureReason,proto3,enum=veil.v1.WsAuthFailureReasonV3" json:"failure_reason,omitempty"`
	CanonicalNodeOrigin  string                `protobuf:"bytes,9,opt,name=canonical_node_origin,json=canonicalNodeOrigin,proto3" json:"canonical_node_origin,omitempty"` // Exact configured origin for client comparison.
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AuthResultV3) Reset() {
	*x = AuthResultV3{}
	mi := &file_veil_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResultV3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResultV3) ProtoMessage() {}

func (x *AuthResultV3) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResultV3.ProtoReflect.Descriptor instead.
func (*AuthResultV3) Descriptor() ([]byte, []int) {
	return file_veil_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *AuthResultV3) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *AuthResultV3) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthResultV3) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *AuthResultV3) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *AuthResultV3) GetPerDeviceSecure() bool {
	if x != nil {
		return x.PerDeviceSecure
	}
	return false
}

func (x *AuthResultV3) GetDeviceBindingVersion() uint64 {
	if x != nil {
		return x.DeviceBindingVersion
	}
	return 0
}

func (x *AuthResultV3) GetDeviceBindingStatus() DeviceBindingStatus {
	if x != nil {
		return x.DeviceBindingStatus
	}
	return DeviceBindingStatus_DEVICE_BINDING_STATUS_UNSPECIFIED
}

func (x *AuthResultV3) GetFailureReason() WsAuthFailureReasonV3 {
	if x != nil {
		return x.FailureReason
	}
	return WsAuthFailureReasonV3_WS_AUTH_FAILURE_REASON_V3_UNSPECIFIED
}

func (x *AuthResultV3) GetCanonicalNodeOrigin() string {
	if x != nil {
		return x.CanonicalNodeOrigin
	}
	return ""
}

var File_veil_v1_auth_proto protoreflect.FileDescriptor

const file_veil_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x12veil/v1/auth.proto\x12\aveil.v1\"-\n" +
	"\rAuthChallenge\x12\x1c\n" +
	"\tchallenge\x18\x01 \x01(\fR\tchallenge\"\xef\x02\n" +
	"\fAuthResponse\x12!\n" +
	"\fidentity_key\x18\x01 \x01(\fR\videntityKey\x12\x1f\n" +
	"\vsigning_key\x18\x02 \x01(\fR\n" +
	"signingKey\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\fR\bdeviceId\x12\x1f\n" +
	"\vdevice_name\x18\x05 \x01(\tR\n" +
	"deviceName\x12%\n" +
	"\x0eclient_version\x18\x06 \x01(\tR\rclientVersion\x12?\n" +
	"\x0edevice_binding\x18\a \x01(\v2\x18.veil.v1.DeviceBindingV1R\rdeviceBinding\x12)\n" +
	"\x10device_signature\x18\b \x01(\fR\x0fdeviceSignature\x12,\n" +
	"\x12node_access_invite\x18\t \x01(\fR\x10nodeAccessInvite\"\x83\x03\n" +
	"\n" +
	"AuthResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1c\n" +
	"\auser_id\x18\x02 \x01(\tH\x00R\x06userId\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\x03 \x01(\tH\x01R\ferrorMessage\x88\x01\x01\x12*\n" +
	"\x11per_device_secure\x18\x04 \x01(\bR\x0fperDeviceSecure\x124\n" +
	"\x16device_binding_version\x18\x05 \x01(\x04R\x14deviceBindingVersion\x12P\n" +
	"\x15device_binding_status\x18\x06 \x01(\x0e2\x1c.veil.v1.DeviceBindingStatusR\x13deviceBindingStatus\x12A\n" +
	"\x0efailure_reason\x18\a \x01(\x0e2\x1a.veil.v1.AuthFailureReasonR\rfailureReasonB\n" +
	"\n" +
	"\b_user_idB\x10\n" +
	"\x0e_error_message\"\xad\x02\n" +
	"\x0fDeviceBindingV1\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\fR\bdeviceId\x12.\n" +
	"\x13device_identity_key\x18\x02 \x01(\fR\x11deviceIdentityKey\x12,\n" +
	"\x12device_signing_key\x18\x03 \x01(\fR\x10deviceSigningKey\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x04R\aversion\x12\"\n" +
	"\fcapabilities\x18\x05 \x01(\x04R\fcapabilities\x124\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1c.veil.v1.DeviceBindingStatusR\x06status\x12+\n" +
	"\x11account_signature\x18\a \x01(\fR\x10accountSignature\"\xf0\x02\n" +
	"\x14DeviceDirectoryEntry\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\fR\bdeviceId\x127\n" +
	"\abinding\x18\x04 \x01(\v2\x18.veil.v1.DeviceBindingV1H\x00R\abinding\x88\x01\x01\x12\x1a\n" +
	"\beligible\x18\x05 \x01(\bR\beligible\x12.\n" +
	"\x10exclusion_reason\x18\x06 \x01(\tH\x01R\x0fexclusionReason\x88\x01\x01\x120\n" +
	"\x14account_identity_key\x18\a \x01(\fR\x12accountIdentityKey\x12.\n" +
	"\x13account_signing_key\x18\b \x01(\fR\x11accountSigningKeyB\n" +
	"\n" +
	"\b_bindingB\x13\n" +
	"\x11_exclusion_reason\"\xee\x02\n" +
	"\x1bConversationDeviceDirectory\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12%\n" +
	"\x0eroster_version\x18\x02 \x01(\x04R\rrosterVersion\x12+\n" +
	"\x11roster_commitment\x18\x03 \x01(\fR\x10rosterCommitment\x12\x14\n" +
	"\x05ready\x18\x04 \x01(\bR\x05ready\x12\x1b\n" +
	"\x06reason\x18\x05 \x01(\tH\x00R\x06reason\x88\x01\x01\x123\n" +
	"\x15required_capabilities\x18\x06 \x01(\x04R\x14requiredCapabilities\x12&\n" +
	"\x0fmember_user_ids\x18\a \x03(\tR\rmemberUserIds\x127\n" +
	"\adevices\x18\b \x03(\v2\x1d.veil.v1.DeviceDirectoryEntryR\adevicesB\t\n" +
	"\a_reason\"\xd1\x01\n" +
	"\x0eRegisterDevice\x12!\n" +
	"\fidentity_key\x18\x01 \x01(\fR\videntityKey\x12\x1f\n" +
	"\vsigning_key\x18\x02 \x01(\fR\n" +
	"signingKey\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\fR\bdeviceId\x12\x1f\n" +
	"\vdevice_name\x18\x04 \x01(\tR\n" +
	"deviceName\x12*\n" +
	"\x0elink_signature\x18\x05 \x01(\fH\x00R\rlinkSignature\x88\x01\x01B\x11\n" +
	"\x0f_link_signature\"\x9b\x01\n" +
	"\x0fAuthChallengeV3\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12)\n" +
	"\x10server_ephemeral\x18\x02 \x01(\fR\x0fserverEphemeral\x122\n" +
	"\x15canonical_node_origin\x18\x03 \x01(\tR\x13canonicalNodeOrigin\"\x8f\x04\n" +
	"\x0eAuthResponseV3\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12!\n" +
	"\fidentity_key\x18\x02 \x01(\fR\videntityKey\x12\x1f\n" +
	"\vsigning_key\x18\x03 \x01(\fR\n" +
	"signingKey\x126\n" +
	"\x17account_proof_signature\x18\x04 \x01(\fR\x15accountProofSignature\x12\x1b\n" +
	"\tdevice_id\x18\x05 \x01(\fR\bdeviceId\x12\x1f\n" +
	"\vdevice_name\x18\x06 \x01(\tR\n" +
	"deviceName\x12%\n" +
	"\x0eclient_version\x18\a \x01(\tR\rclientVersion\x12?\n" +
	"\x0edevice_binding\x18\b \x01(\v2\x18.veil.v1.DeviceBindingV1R\rdeviceBinding\x124\n" +
	"\x16device_proof_signature\x18\t \x01(\fR\x14deviceProofSignature\x12P\n" +
	"\x13registration_intent\x18\n" +
	" \x01(\x0e2\x1f.veil.v1.WsRegistrationIntentV3R\x12registrationIntent\x12(\n" +
	"\x10node_access_pass\x18\v \x01(\fR\x0enodeAccessPass\"\xe8\x03\n" +
	"\fAuthResultV3\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1c\n" +
	"\auser_id\x18\x03 \x01(\tH\x00R\x06userId\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\x04 \x01(\tH\x01R\ferrorMessage\x88\x01\x01\x12*\n" +
	"\x11per_device_secure\x18\x05 \x01(\bR\x0fperDeviceSecure\x124\n" +
	"\x16device_binding_version\x18\x06 \x01(\x04R\x14deviceBindingVersion\x12P\n" +
	"\x15device_binding_status\x18\a \x01(\x0e2\x1c.veil.v1.DeviceBindingStatusR\x13deviceBindingStatus\x12E\n" +
	"\x0efailure_reason\x18\b \x01(\x0e2\x1e.veil.v1.WsAuthFailureReasonV3R\rfailureReason\x122\n" +
	"\x15canonical_node_origin\x18\t \x01(\tR\x13canonicalNodeOriginB\n" +
	"\n" +
	"\b_user_idB\x10\n" +
	"\x0e_error_message*\xbc\x01\n" +
	"\x11AuthFailureReason\x12#\n" +
	"\x1fAUTH_FAILURE_REASON_UNSPECIFIED\x10\x00\x12-\n" +
	")AUTH_FAILURE_REASON_AUTHENTICATION_FAILED\x10\x01\x12+\n" +
	"'AUTH_FAILURE_REASON_REGISTRATION_CLOSED\x10\x02\x12&\n" +
	"\"AUTH_FAILURE_REASON_INVITE_INVALID\x10\x03*\x80\x01\n" +
	"\x10DeviceCapability\x12!\n" +
	"\x1dDEVICE_CAPABILITY_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fDEVICE_CAPABILITY_SENDER_KEY_V5\x10\x01\x12$\n" +
	" DEVICE_CAPABILITY_SEALED_SKDM_V3\x10\x02*\xcf\x01\n" +
	"\x13DeviceBindingStatus\x12%\n" +
	"!DEVICE_BINDING_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cDEVICE_BINDING_STATUS_ACTIVE\x10\x01\x12\"\n" +
	"\x1eDEVICE_BINDING_STATUS_EXCLUDED\x10\x02\x12!\n" +
	"\x1dDEVICE_BINDING_STATUS_REVOKED\x10\x03\x12(\n" +
	"$DEVICE_BINDING_STATUS_LEGACY_UNBOUND\x10\x04*\xb3\x01\n" +
	"\x16WsRegistrationIntentV3\x12)\n" +
	"%WS_REGISTRATION_INTENT_V3_UNSPECIFIED\x10\x00\x12&\n" +
	"\"WS_REGISTRATION_INTENT_V3_EXISTING\x10\x01\x12\"\n" +
	"\x1eWS_REGISTRATION_INTENT_V3_OPEN\x10\x02\x12\"\n" +
	"\x1eWS_REGISTRATION_INTENT_V3_PASS\x10\x03*\xe2\x01\n" +
	"\x15WsAuthFailureReasonV3\x12)\n" +
	"%WS_AUTH_FAILURE_REASON_V3_UNSPECIFIED\x10\x00\x123\n" +
	"/WS_AUTH_FAILURE_REASON_V3_AUTHENTICATION_FAILED\x10\x01\x121\n" +
	"-WS_AUTH_FAILURE_REASON_V3_REGISTRATION_CLOSED\x10\x02\x126\n" +
	"2WS_AUTH_FAILURE_REASON_V3_NODE_ACCESS_PASS_INVALID\x10\x03B2Z0github.com/NaveLIL/veil/veil-server/pkg/proto/v1b\x06proto3"

var (
	file_veil_v1_auth_proto_rawDescOnce sync.Once
	file_veil_v1_auth_proto_rawDescData []byte
)

func file_veil_v1_auth_proto_rawDescGZIP() []byte {
	file_veil_v1_auth_proto_rawDescOnce.Do(func() {
		file_veil_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_veil_v1_auth_proto_rawDesc), len(file_veil_v1_auth_proto_rawDesc)))
	})
	return file_veil_v1_auth_proto_rawDescData
}

var file_veil_v1_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_veil_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_veil_v1_auth_proto_goTypes = []any{
	(AuthFailureReason)(0),              // 0: veil.v1.AuthFailureReason
	(DeviceCapability)(0),               // 1: veil.v1.DeviceCapability
	(DeviceBindingStatus)(0),            // 2: veil.v1.DeviceBindingStatus
	(WsRegistrationIntentV3)(0),         // 3: veil.v1.WsRegistrationIntentV3
	(WsAuthFailureReasonV3)(0),          // 4: veil.v1.WsAuthFailureReasonV3
	(*AuthChallenge)(nil),               // 5: veil.v1.AuthChallenge
	(*AuthResponse)(nil),                // 6: veil.v1.AuthResponse
	(*AuthResult)(nil),                  // 7: veil.v1.AuthResult
	(*DeviceBindingV1)(nil),             // 8: veil.v1.DeviceBindingV1
	(*DeviceDirectoryEntry)(nil),        // 9: veil.v1.DeviceDirectoryEntry
	(*ConversationDeviceDirectory)(nil), // 10: veil.v1.ConversationDeviceDirectory
	(*RegisterDevice)(nil),              // 11: veil.v1.RegisterDevice
	(*AuthChallengeV3)(nil),             // 12: veil.v1.AuthChallengeV3
	(*AuthResponseV3)(nil),              // 13: veil.v1.AuthResponseV3
	(*AuthResultV3)(nil),                // 14: veil.v1.AuthResultV3
}
var file_veil_v1_auth_proto_depIdxs = []int32{
	8,  // 0: veil.v1.AuthResponse.device_binding:type_name -> veil.v1.DeviceBindingV1
	2,  // 1: veil.v1.AuthResult.device_binding_status:type_name -> veil.v1.DeviceBindingStatus
	0,  // 2: veil.v1.AuthResult.failure_reason:type_name -> veil.v1.AuthFailureReason
	2,  // 3: veil.v1.DeviceBindingV1.status:type_name -> veil.v1.DeviceBindingStatus
	8,  // 4: veil.v1.DeviceDirectoryEntry.binding:type_name -> veil.v1.DeviceBindingV1
	9,  // 5: veil.v1.ConversationDeviceDirectory.devices:type_name -> veil.v1.DeviceDirectoryEntry
	8,  // 6: veil.v1.AuthResponseV3.device_binding:type_name -> veil.v1.DeviceBindingV1
	3,  // 7: veil.v1.AuthResponseV3.registration_intent:type_name -> veil.v1.WsRegistrationIntentV3
	2,  // 8: veil.v1.AuthResultV3.device_binding_status:type_name -> veil.v1.DeviceBindingStatus
	4,  // 9: veil.v1.AuthResultV3.failure_reason:type_name -> veil.v1.WsAuthFailureReasonV3
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_veil_v1_auth_proto_init() }
func file_veil_v1_auth_proto_init() {
	if File_veil_v1_auth_proto != nil {
		return
	}
	file_veil_v1_auth_proto_msgTypes[2].OneofWrappers = []any{}
	file_veil_v1_auth_proto_msgTypes[4].OneofWrappers = []any{}
	file_veil_v1_auth_proto_msgTypes[5].OneofWrappers = []any{}
	file_veil_v1_auth_proto_msgTypes[6].OneofWrappers = []any{}
	file_veil_v1_auth_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_veil_v1_auth_proto_rawDesc), len(file_veil_v1_auth_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_veil_v1_auth_proto_goTypes,
		DependencyIndexes: file_veil_v1_auth_proto_depIdxs,
		EnumInfos:         file_veil_v1_auth_proto_enumTypes,
		MessageInfos:      file_veil_v1_auth_proto_msgTypes,
	}.Build()
	File_veil_v1_auth_proto = out.File
	file_veil_v1_auth_proto_goTypes = nil
	file_veil_v1_auth_proto_depIdxs = nil
}
