// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: veil/v1/auth.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Сервер отправляет challenge при подключении
type AuthChallenge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Challenge     []byte                 `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"` // 32 bytes random
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthChallenge) Reset() {
	*x = AuthChallenge{}
	mi := &file_veil_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthChallenge) ProtoMessage() {}

func (x *AuthChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthChallenge.ProtoReflect.Descriptor instead.
func (*AuthChallenge) Descriptor() ([]byte, []int) {
	return file_veil_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthChallenge) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

// Клиент подписывает challenge и отправляет identity
type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityKey   []byte                 `protobuf:"bytes,1,opt,name=identity_key,json=identityKey,proto3" json:"identity_key,omitempty"`       // X25519 public key (32 bytes)
	SigningKey    []byte                 `protobuf:"bytes,2,opt,name=signing_key,json=signingKey,proto3" json:"signing_key,omitempty"`          // Ed25519 public key (32 bytes)
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`                              // Ed25519 signature of challenge
	DeviceId      []byte                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                // Unique device ID (16 bytes UUID)
	DeviceName    string                 `protobuf:"bytes,5,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`          // Human-readable: "Pixel 9", "MacBook Pro"
	ClientVersion string                 `protobuf:"bytes,6,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"` // "veil-desktop/1.0.0"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_veil_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_veil_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthResponse) GetIdentityKey() []byte {
	if x != nil {
		return x.IdentityKey
	}
	return nil
}

func (x *AuthResponse) GetSigningKey() []byte {
	if x != nil {
		return x.SigningKey
	}
	return nil
}

func (x *AuthResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AuthResponse) GetDeviceId() []byte {
	if x != nil {
		return x.DeviceId
	}
	return nil
}

func (x *AuthResponse) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *AuthResponse) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

// Результат аутентификации
type AuthResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UserId        *string                `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	ErrorMessage  *string                `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResult) Reset() {
	*x = AuthResult{}
	mi := &file_veil_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResult) ProtoMessage() {}

func (x *AuthResult) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResult.ProtoReflect.Descriptor instead.
func (*AuthResult) Descriptor() ([]byte, []int) {
	return file_veil_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AuthResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthResult) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *AuthResult) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

// Регистрация нового устройства (link existing account)
type RegisterDevice struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	IdentityKey []byte                 `protobuf:"bytes,1,opt,name=identity_key,json=identityKey,proto3" json:"identity_key,omitempty"`
	SigningKey  []byte                 `protobuf:"bytes,2,opt,name=signing_key,json=signingKey,proto3" json:"signing_key,omitempty"`
	DeviceId    []byte                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DeviceName  string                 `protobuf:"bytes,4,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Для привязки к существующему аккаунту:
	LinkSignature []byte `protobuf:"bytes,5,opt,name=link_signature,json=linkSignature,proto3,oneof" json:"link_signature,omitempty"` // Подпись от master device
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDevice) Reset() {
	*x = RegisterDevice{}
	mi := &file_veil_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDevice) ProtoMessage() {}

func (x *RegisterDevice) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDevice.ProtoReflect.Descriptor instead.
func (*RegisterDevice) Descriptor() ([]byte, []int) {
	return file_veil_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterDevice) GetIdentityKey() []byte {
	if x != nil {
		return x.IdentityKey
	}
	return nil
}

func (x *RegisterDevice) GetSigningKey() []byte {
	if x != nil {
		return x.SigningKey
	}
	return nil
}

func (x *RegisterDevice) GetDeviceId() []byte {
	if x != nil {
		return x.DeviceId
	}
	return nil
}

func (x *RegisterDevice) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *RegisterDevice) GetLinkSignature() []byte {
	if x != nil {
		return x.LinkSignature
	}
	return nil
}

var File_veil_v1_auth_proto protoreflect.FileDescriptor

const file_veil_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x12veil/v1/auth.proto\x12\aveil.v1\"-\n" +
	"\rAuthChallenge\x12\x1c\n" +
	"\tchallenge\x18\x01 \x01(\fR\tchallenge\"\xd5\x01\n" +
	"\fAuthResponse\x12!\n" +
	"\fidentity_key\x18\x01 \x01(\fR\videntityKey\x12\x1f\n" +
	"\vsigning_key\x18\x02 \x01(\fR\n" +
	"signingKey\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\fR\bdeviceId\x12\x1f\n" +
	"\vdevice_name\x18\x05 \x01(\tR\n" +
	"deviceName\x12%\n" +
	"\x0eclient_version\x18\x06 \x01(\tR\rclientVersion\"\x8c\x01\n" +
	"\n" +
	"AuthResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1c\n" +
	"\auser_id\x18\x02 \x01(\tH\x00R\x06userId\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\x03 \x01(\tH\x01R\ferrorMessage\x88\x01\x01B\n" +
	"\n" +
	"\b_user_idB\x10\n" +
	"\x0e_error_message\"\xd1\x01\n" +
	"\x0eRegisterDevice\x12!\n" +
	"\fidentity_key\x18\x01 \x01(\fR\videntityKey\x12\x1f\n" +
	"\vsigning_key\x18\x02 \x01(\fR\n" +
	"signingKey\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\fR\bdeviceId\x12\x1f\n" +
	"\vdevice_name\x18\x04 \x01(\tR\n" +
	"deviceName\x12*\n" +
	"\x0elink_signature\x18\x05 \x01(\fH\x00R\rlinkSignature\x88\x01\x01B\x11\n" +
	"\x0f_link_signatureB.Z,github.com/AegisSec/veil-server/pkg/proto/v1b\x06proto3"

var (
	file_veil_v1_auth_proto_rawDescOnce sync.Once
	file_veil_v1_auth_proto_rawDescData []byte
)

func file_veil_v1_auth_proto_rawDescGZIP() []byte {
	file_veil_v1_auth_proto_rawDescOnce.Do(func() {
		file_veil_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_veil_v1_auth_proto_rawDesc), len(file_veil_v1_auth_proto_rawDesc)))
	})
	return file_veil_v1_auth_proto_rawDescData
}

var file_veil_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_veil_v1_auth_proto_goTypes = []any{
	(*AuthChallenge)(nil),  // 0: veil.v1.AuthChallenge
	(*AuthResponse)(nil),   // 1: veil.v1.AuthResponse
	(*AuthResult)(nil),     // 2: veil.v1.AuthResult
	(*RegisterDevice)(nil), // 3: veil.v1.RegisterDevice
}
var file_veil_v1_auth_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_veil_v1_auth_proto_init() }
func file_veil_v1_auth_proto_init() {
	if File_veil_v1_auth_proto != nil {
		return
	}
	file_veil_v1_auth_proto_msgTypes[2].OneofWrappers = []any{}
	file_veil_v1_auth_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_veil_v1_auth_proto_rawDesc), len(file_veil_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_veil_v1_auth_proto_goTypes,
		DependencyIndexes: file_veil_v1_auth_proto_depIdxs,
		MessageInfos:      file_veil_v1_auth_proto_msgTypes,
	}.Build()
	File_veil_v1_auth_proto = out.File
	file_veil_v1_auth_proto_goTypes = nil
	file_veil_v1_auth_proto_depIdxs = nil
}
