// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: veil/v1/chat.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MESSAGE_TYPE_TEXT       MessageType = 0
	MessageType_MESSAGE_TYPE_IMAGE      MessageType = 1
	MessageType_MESSAGE_TYPE_FILE       MessageType = 2
	MessageType_MESSAGE_TYPE_VOICE_NOTE MessageType = 3
	MessageType_MESSAGE_TYPE_VIEW_ONCE  MessageType = 4
	MessageType_MESSAGE_TYPE_SYSTEM     MessageType = 5
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_TEXT",
		1: "MESSAGE_TYPE_IMAGE",
		2: "MESSAGE_TYPE_FILE",
		3: "MESSAGE_TYPE_VOICE_NOTE",
		4: "MESSAGE_TYPE_VIEW_ONCE",
		5: "MESSAGE_TYPE_SYSTEM",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_TEXT":       0,
		"MESSAGE_TYPE_IMAGE":      1,
		"MESSAGE_TYPE_FILE":       2,
		"MESSAGE_TYPE_VOICE_NOTE": 3,
		"MESSAGE_TYPE_VIEW_ONCE":  4,
		"MESSAGE_TYPE_SYSTEM":     5,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_veil_v1_chat_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_veil_v1_chat_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_veil_v1_chat_proto_rawDescGZIP(), []int{0}
}

type MessageEvent_EventType int32

const (
	MessageEvent_NEW     MessageEvent_EventType = 0
	MessageEvent_EDITED  MessageEvent_EventType = 1
	MessageEvent_DELETED MessageEvent_EventType = 2
)

// Enum value maps for MessageEvent_EventType.
var (
	MessageEvent_EventType_name = map[int32]string{
		0: "NEW",
		1: "EDITED",
		2: "DELETED",
	}
	MessageEvent_EventType_value = map[string]int32{
		"NEW":     0,
		"EDITED":  1,
		"DELETED": 2,
	}
)

func (x MessageEvent_EventType) Enum() *MessageEvent_EventType {
	p := new(MessageEvent_EventType)
	*p = x
	return p
}

func (x MessageEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_veil_v1_chat_proto_enumTypes[1].Descriptor()
}

func (MessageEvent_EventType) Type() protoreflect.EnumType {
	return &file_veil_v1_chat_proto_enumTypes[1]
}

func (x MessageEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageEvent_EventType.Descriptor instead.
func (MessageEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_veil_v1_chat_proto_rawDescGZIP(), []int{7, 0}
}

// Клиент → сервер: отправка сообщения
type SendMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // UUID (DM, group, channel — один тип)
	Ciphertext     []byte                 `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`                               // E2E зашифрованный payload
	Header         []byte                 `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`                                       // Encrypted ratchet header (для DM)
	MsgType        MessageType            `protobuf:"varint,4,opt,name=msg_type,json=msgType,proto3,enum=veil.v1.MessageType" json:"msg_type,omitempty"`
	ReplyToId      *string                `protobuf:"bytes,5,opt,name=reply_to_id,json=replyToId,proto3,oneof" json:"reply_to_id,omitempty"`
	TtlSeconds     *uint32                `protobuf:"varint,6,opt,name=ttl_seconds,json=ttlSeconds,proto3,oneof" json:"ttl_seconds,omitempty"` // Disappearing message TTL
	Attachments    []*EncryptedAttachment `protobuf:"bytes,7,rep,name=attachments,proto3" json:"attachments,omitempty"`
	// Для sealed sender: ciphertext содержит sender info внутри
	Sealed        bool `protobuf:"varint,8,opt,name=sealed,proto3" json:"sealed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessage) Reset() {
	*x = SendMessage{}
	mi := &file_veil_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessage) ProtoMessage() {}

func (x *SendMessage) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessage.ProtoReflect.Descriptor instead.
func (*SendMessage) Descriptor() ([]byte, []int) {
	return file_veil_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessage) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *SendMessage) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *SendMessage) GetHeader() []byte {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SendMessage) GetMsgType() MessageType {
	if x != nil {
		return x.MsgType
	}
	return MessageType_MESSAGE_TYPE_TEXT
}

func (x *SendMessage) GetReplyToId() string {
	if x != nil && x.ReplyToId != nil {
		return *x.ReplyToId
	}
	return ""
}

func (x *SendMessage) GetTtlSeconds() uint32 {
	if x != nil && x.TtlSeconds != nil {
		return *x.TtlSeconds
	}
	return 0
}

func (x *SendMessage) GetAttachments() []*EncryptedAttachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *SendMessage) GetSealed() bool {
	if x != nil {
		return x.Sealed
	}
	return false
}

type EncryptedAttachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`                // ID загруженного файла
	EncryptedKey  []byte                 `protobuf:"bytes,2,opt,name=encrypted_key,json=encryptedKey,proto3" json:"encrypted_key,omitempty"` // Ключ шифрования файла (зашифрован для получателя)
	Nonce         []byte                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Size          uint64                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	ContentType   string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // MIME type (зашифрован? нет — server needs for thumbnails)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedAttachment) Reset() {
	*x = EncryptedAttachment{}
	mi := &file_veil_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedAttachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedAttachment) ProtoMessage() {}

func (x *EncryptedAttachment) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedAttachment.ProtoReflect.Descriptor instead.
func (*EncryptedAttachment) Descriptor() ([]byte, []int) {
	return file_veil_v1_chat_proto_rawDescGZIP(), []int{1}
}

func (x *EncryptedAttachment) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *EncryptedAttachment) GetEncryptedKey() []byte {
	if x != nil {
		return x.EncryptedKey
	}
	return nil
}

func (x *EncryptedAttachment) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *EncryptedAttachment) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *EncryptedAttachment) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// Сервер → клиент: подтверждение отправки
type MessageAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MessageId       string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ServerTimestamp uint64                 `protobuf:"varint,2,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	RefSeq          uint64                 `protobuf:"varint,3,opt,name=ref_seq,json=refSeq,proto3" json:"ref_seq,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageAck) Reset() {
	*x = MessageAck{}
	mi := &file_veil_v1_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAck) ProtoMessage() {}

func (x *MessageAck) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAck.ProtoReflect.Descriptor instead.
func (*MessageAck) Descriptor() ([]byte, []int) {
	return file_veil_v1_chat_proto_rawDescGZIP(), []int{2}
}

func (x *MessageAck) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageAck) GetServerTimestamp() uint64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

func (x *MessageAck) GetRefSeq() uint64 {
	if x != nil {
		return x.RefSeq
	}
	return 0
}

// Сервер → клиент: сообщение доставлено получателю
type MessageDelivered struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Timestamp      uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageDelivered) Reset() {
	*x = MessageDelivered{}
	mi := &file_veil_v1_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDelivered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDelivered) ProtoMessage() {}

func (x *MessageDelivered) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDelivered.ProtoReflect.Descriptor instead.
func (*MessageDelivered) Descriptor() ([]byte, []int) {
	return file_veil_v1_chat_proto_rawDescGZIP(), []int{3}
}

func (x *MessageDelivered) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageDelivered) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageDelivered) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Клиент ↔ сервер: отметка о прочтении
type MessageRead struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	LastReadId     string                 `protobuf:"bytes,2,opt,name=last_read_id,json=lastReadId,proto3" json:"last_read_id,omitempty"` // ID последнего прочитанного сообщения
	Timestamp      uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageRead) Reset() {
	*x = MessageRead{}
	mi := &file_veil_v1_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRead) ProtoMessage() {}

func (x *MessageRead) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRead.ProtoReflect.Descriptor instead.
func (*MessageRead) Descriptor() ([]byte, []int) {
	return file_veil_v1_chat_proto_rawDescGZIP(), []int{4}
}

func (x *MessageRead) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageRead) GetLastReadId() string {
	if x != nil {
		return x.LastReadId
	}
	return ""
}

func (x *MessageRead) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Клиент → сервер: редактирование сообщения
type EditMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	NewCiphertext  []byte                 `protobuf:"bytes,3,opt,name=new_ciphertext,json=newCiphertext,proto3" json:"new_ciphertext,omitempty"`
	NewHeader      []byte                 `protobuf:"bytes,4,opt,name=new_header,json=newHeader,proto3" json:"new_header,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EditMessage) Reset() {
	*x = EditMessage{}
	mi := &file_veil_v1_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMessage) ProtoMessage() {}

func (x *EditMessage) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMessage.ProtoReflect.Descriptor instead.
func (*EditMessage) Descriptor() ([]byte, []int) {
	return file_veil_v1_chat_proto_rawDescGZIP(), []int{5}
}

func (x *EditMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *EditMessage) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *EditMessage) GetNewCiphertext() []byte {
	if x != nil {
		return x.NewCiphertext
	}
	return nil
}

func (x *EditMessage) GetNewHeader() []byte {
	if x != nil {
		return x.NewHeader
	}
	return nil
}

// Клиент → сервер: удаление сообщения
type DeleteMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteMessage) Reset() {
	*x = DeleteMessage{}
	mi := &file_veil_v1_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessage) ProtoMessage() {}

func (x *DeleteMessage) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessage.ProtoReflect.Descriptor instead.
func (*DeleteMessage) Descriptor() ([]byte, []int) {
	return file_veil_v1_chat_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DeleteMessage) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

// Сервер → клиент: событие о сообщении (новое, edit, delete)
type MessageEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EventType         MessageEvent_EventType `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=veil.v1.MessageEvent_EventType" json:"event_type,omitempty"`
	MessageId         string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ConversationId    string                 `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	SenderIdentityKey []byte                 `protobuf:"bytes,4,opt,name=sender_identity_key,json=senderIdentityKey,proto3" json:"sender_identity_key,omitempty"`
	SenderUsername    string                 `protobuf:"bytes,5,opt,name=sender_username,json=senderUsername,proto3" json:"sender_username,omitempty"`
	ServerTimestamp   uint64                 `protobuf:"varint,6,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	// Для NEW и EDITED:
	Ciphertext  []byte                 `protobuf:"bytes,7,opt,name=ciphertext,proto3,oneof" json:"ciphertext,omitempty"`
	Header      []byte                 `protobuf:"bytes,8,opt,name=header,proto3,oneof" json:"header,omitempty"`
	MsgType     *MessageType           `protobuf:"varint,9,opt,name=msg_type,json=msgType,proto3,enum=veil.v1.MessageType,oneof" json:"msg_type,omitempty"`
	ReplyToId   *string                `protobuf:"bytes,10,opt,name=reply_to_id,json=replyToId,proto3,oneof" json:"reply_to_id,omitempty"`
	TtlSeconds  *uint32                `protobuf:"varint,11,opt,name=ttl_seconds,json=ttlSeconds,proto3,oneof" json:"ttl_seconds,omitempty"`
	Attachments []*EncryptedAttachment `protobuf:"bytes,12,rep,name=attachments,proto3" json:"attachments,omitempty"`
	Sealed      *bool                  `protobuf:"varint,13,opt,name=sealed,proto3,oneof" json:"sealed,omitempty"`
	// Для EDITED — ID оригинального сообщения:
	EditTimestamp *uint64 `protobuf:"varint,14,opt,name=edit_timestamp,json=editTimestamp,proto3,oneof" json:"edit_timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageEvent) Reset() {
	*x = MessageEvent{}
	mi := &file_veil_v1_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEvent) ProtoMessage() {}

func (x *MessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEvent.ProtoReflect.Descriptor instead.
func (*MessageEvent) Descriptor() ([]byte, []int) {
	return file_veil_v1_chat_proto_rawDescGZIP(), []int{7}
}

func (x *MessageEvent) GetEventType() MessageEvent_EventType {
	if x != nil {
		return x.EventType
	}
	return MessageEvent_NEW
}

func (x *MessageEvent) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageEvent) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageEvent) GetSenderIdentityKey() []byte {
	if x != nil {
		return x.SenderIdentityKey
	}
	return nil
}

func (x *MessageEvent) GetSenderUsername() string {
	if x != nil {
		return x.SenderUsername
	}
	return ""
}

func (x *MessageEvent) GetServerTimestamp() uint64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

func (x *MessageEvent) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *MessageEvent) GetHeader() []byte {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *MessageEvent) GetMsgType() MessageType {
	if x != nil && x.MsgType != nil {
		return *x.MsgType
	}
	return MessageType_MESSAGE_TYPE_TEXT
}

func (x *MessageEvent) GetReplyToId() string {
	if x != nil && x.ReplyToId != nil {
		return *x.ReplyToId
	}
	return ""
}

func (x *MessageEvent) GetTtlSeconds() uint32 {
	if x != nil && x.TtlSeconds != nil {
		return *x.TtlSeconds
	}
	return 0
}

func (x *MessageEvent) GetAttachments() []*EncryptedAttachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *MessageEvent) GetSealed() bool {
	if x != nil && x.Sealed != nil {
		return *x.Sealed
	}
	return false
}

func (x *MessageEvent) GetEditTimestamp() uint64 {
	if x != nil && x.EditTimestamp != nil {
		return *x.EditTimestamp
	}
	return 0
}

// Prekey bundle for X3DH session establishment
type PreKeyBundle struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	IdentityKey           []byte                 `protobuf:"bytes,1,opt,name=identity_key,json=identityKey,proto3" json:"identity_key,omitempty"`                                 // IK (X25519)
	SignedPrekey          []byte                 `protobuf:"bytes,2,opt,name=signed_prekey,json=signedPrekey,proto3" json:"signed_prekey,omitempty"`                              // SPK (X25519)
	SignedPrekeySignature []byte                 `protobuf:"bytes,3,opt,name=signed_prekey_signature,json=signedPrekeySignature,proto3" json:"signed_prekey_signature,omitempty"` // Ed25519 sig of SPK
	SignedPrekeyId        uint32                 `protobuf:"varint,4,opt,name=signed_prekey_id,json=signedPrekeyId,proto3" json:"signed_prekey_id,omitempty"`
	OneTimePrekey         []byte                 `protobuf:"bytes,5,opt,name=one_time_prekey,json=oneTimePrekey,proto3,oneof" json:"one_time_prekey,omitempty"` // OPK (X25519), may be absent
	OneTimePrekeyId       *uint32                `protobuf:"varint,6,opt,name=one_time_prekey_id,json=oneTimePrekeyId,proto3,oneof" json:"one_time_prekey_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PreKeyBundle) Reset() {
	*x = PreKeyBundle{}
	mi := &file_veil_v1_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreKeyBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreKeyBundle) ProtoMessage() {}

func (x *PreKeyBundle) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreKeyBundle.ProtoReflect.Descriptor instead.
func (*PreKeyBundle) Descriptor() ([]byte, []int) {
	return file_veil_v1_chat_proto_rawDescGZIP(), []int{8}
}

func (x *PreKeyBundle) GetIdentityKey() []byte {
	if x != nil {
		return x.IdentityKey
	}
	return nil
}

func (x *PreKeyBundle) GetSignedPrekey() []byte {
	if x != nil {
		return x.SignedPrekey
	}
	return nil
}

func (x *PreKeyBundle) GetSignedPrekeySignature() []byte {
	if x != nil {
		return x.SignedPrekeySignature
	}
	return nil
}

func (x *PreKeyBundle) GetSignedPrekeyId() uint32 {
	if x != nil {
		return x.SignedPrekeyId
	}
	return 0
}

func (x *PreKeyBundle) GetOneTimePrekey() []byte {
	if x != nil {
		return x.OneTimePrekey
	}
	return nil
}

func (x *PreKeyBundle) GetOneTimePrekeyId() uint32 {
	if x != nil && x.OneTimePrekeyId != nil {
		return *x.OneTimePrekeyId
	}
	return 0
}

// Запрос prekey bundle для начала сессии с пользователем
type PreKeyRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TargetIdentityKey []byte                 `protobuf:"bytes,1,opt,name=target_identity_key,json=targetIdentityKey,proto3" json:"target_identity_key,omitempty"` // Identity key получателя
	TargetDeviceId    []byte                 `protobuf:"bytes,2,opt,name=target_device_id,json=targetDeviceId,proto3,oneof" json:"target_device_id,omitempty"`    // Конкретное устройство (или все)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PreKeyRequest) Reset() {
	*x = PreKeyRequest{}
	mi := &file_veil_v1_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreKeyRequest) ProtoMessage() {}

func (x *PreKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreKeyRequest.ProtoReflect.Descriptor instead.
func (*PreKeyRequest) Descriptor() ([]byte, []int) {
	return file_veil_v1_chat_proto_rawDescGZIP(), []int{9}
}

func (x *PreKeyRequest) GetTargetIdentityKey() []byte {
	if x != nil {
		return x.TargetIdentityKey
	}
	return nil
}

func (x *PreKeyRequest) GetTargetDeviceId() []byte {
	if x != nil {
		return x.TargetDeviceId
	}
	return nil
}

// Распространение Sender Key для группового чата
type SenderKeyDistribution struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConversationId    string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`            // Group/channel ID
	SenderKeyMessage  []byte                 `protobuf:"bytes,2,opt,name=sender_key_message,json=senderKeyMessage,proto3" json:"sender_key_message,omitempty"`    // Encrypted sender key для каждого участника
	Generation        uint32                 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`                                         // Key generation counter
	TargetIdentityKey []byte                 `protobuf:"bytes,4,opt,name=target_identity_key,json=targetIdentityKey,proto3" json:"target_identity_key,omitempty"` // Для кого зашифрован данный sender key
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SenderKeyDistribution) Reset() {
	*x = SenderKeyDistribution{}
	mi := &file_veil_v1_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SenderKeyDistribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenderKeyDistribution) ProtoMessage() {}

func (x *SenderKeyDistribution) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenderKeyDistribution.ProtoReflect.Descriptor instead.
func (*SenderKeyDistribution) Descriptor() ([]byte, []int) {
	return file_veil_v1_chat_proto_rawDescGZIP(), []int{10}
}

func (x *SenderKeyDistribution) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *SenderKeyDistribution) GetSenderKeyMessage() []byte {
	if x != nil {
		return x.SenderKeyMessage
	}
	return nil
}

func (x *SenderKeyDistribution) GetGeneration() uint32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *SenderKeyDistribution) GetTargetIdentityKey() []byte {
	if x != nil {
		return x.TargetIdentityKey
	}
	return nil
}

var File_veil_v1_chat_proto protoreflect.FileDescriptor

const file_veil_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\x12veil/v1/chat.proto\x12\aveil.v1\"\xe2\x02\n" +
	"\vSendMessage\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x02 \x01(\fR\n" +
	"ciphertext\x12\x16\n" +
	"\x06header\x18\x03 \x01(\fR\x06header\x12/\n" +
	"\bmsg_type\x18\x04 \x01(\x0e2\x14.veil.v1.MessageTypeR\amsgType\x12#\n" +
	"\vreply_to_id\x18\x05 \x01(\tH\x00R\treplyToId\x88\x01\x01\x12$\n" +
	"\vttl_seconds\x18\x06 \x01(\rH\x01R\n" +
	"ttlSeconds\x88\x01\x01\x12>\n" +
	"\vattachments\x18\a \x03(\v2\x1c.veil.v1.EncryptedAttachmentR\vattachments\x12\x16\n" +
	"\x06sealed\x18\b \x01(\bR\x06sealedB\x0e\n" +
	"\f_reply_to_idB\x0e\n" +
	"\f_ttl_seconds\"\xa2\x01\n" +
	"\x13EncryptedAttachment\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12#\n" +
	"\rencrypted_key\x18\x02 \x01(\fR\fencryptedKey\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\fR\x05nonce\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x04R\x04size\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\"o\n" +
	"\n" +
	"MessageAck\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12)\n" +
	"\x10server_timestamp\x18\x02 \x01(\x04R\x0fserverTimestamp\x12\x17\n" +
	"\aref_seq\x18\x03 \x01(\x04R\x06refSeq\"x\n" +
	"\x10MessageDelivered\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\"v\n" +
	"\vMessageRead\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12 \n" +
	"\flast_read_id\x18\x02 \x01(\tR\n" +
	"lastReadId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\"\x9b\x01\n" +
	"\vEditMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12%\n" +
	"\x0enew_ciphertext\x18\x03 \x01(\fR\rnewCiphertext\x12\x1d\n" +
	"\n" +
	"new_header\x18\x04 \x01(\fR\tnewHeader\"W\n" +
	"\rDeleteMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\"\xfa\x05\n" +
	"\fMessageEvent\x12>\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2\x1f.veil.v1.MessageEvent.EventTypeR\teventType\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\tR\x0econversationId\x12.\n" +
	"\x13sender_identity_key\x18\x04 \x01(\fR\x11senderIdentityKey\x12'\n" +
	"\x0fsender_username\x18\x05 \x01(\tR\x0esenderUsername\x12)\n" +
	"\x10server_timestamp\x18\x06 \x01(\x04R\x0fserverTimestamp\x12#\n" +
	"\n" +
	"ciphertext\x18\a \x01(\fH\x00R\n" +
	"ciphertext\x88\x01\x01\x12\x1b\n" +
	"\x06header\x18\b \x01(\fH\x01R\x06header\x88\x01\x01\x124\n" +
	"\bmsg_type\x18\t \x01(\x0e2\x14.veil.v1.MessageTypeH\x02R\amsgType\x88\x01\x01\x12#\n" +
	"\vreply_to_id\x18\n" +
	" \x01(\tH\x03R\treplyToId\x88\x01\x01\x12$\n" +
	"\vttl_seconds\x18\v \x01(\rH\x04R\n" +
	"ttlSeconds\x88\x01\x01\x12>\n" +
	"\vattachments\x18\f \x03(\v2\x1c.veil.v1.EncryptedAttachmentR\vattachments\x12\x1b\n" +
	"\x06sealed\x18\r \x01(\bH\x05R\x06sealed\x88\x01\x01\x12*\n" +
	"\x0eedit_timestamp\x18\x0e \x01(\x04H\x06R\reditTimestamp\x88\x01\x01\"-\n" +
	"\tEventType\x12\a\n" +
	"\x03NEW\x10\x00\x12\n" +
	"\n" +
	"\x06EDITED\x10\x01\x12\v\n" +
	"\aDELETED\x10\x02B\r\n" +
	"\v_ciphertextB\t\n" +
	"\a_headerB\v\n" +
	"\t_msg_typeB\x0e\n" +
	"\f_reply_to_idB\x0e\n" +
	"\f_ttl_secondsB\t\n" +
	"\a_sealedB\x11\n" +
	"\x0f_edit_timestamp\"\xc2\x02\n" +
	"\fPreKeyBundle\x12!\n" +
	"\fidentity_key\x18\x01 \x01(\fR\videntityKey\x12#\n" +
	"\rsigned_prekey\x18\x02 \x01(\fR\fsignedPrekey\x126\n" +
	"\x17signed_prekey_signature\x18\x03 \x01(\fR\x15signedPrekeySignature\x12(\n" +
	"\x10signed_prekey_id\x18\x04 \x01(\rR\x0esignedPrekeyId\x12+\n" +
	"\x0fone_time_prekey\x18\x05 \x01(\fH\x00R\roneTimePrekey\x88\x01\x01\x120\n" +
	"\x12one_time_prekey_id\x18\x06 \x01(\rH\x01R\x0foneTimePrekeyId\x88\x01\x01B\x12\n" +
	"\x10_one_time_prekeyB\x15\n" +
	"\x13_one_time_prekey_id\"\x83\x01\n" +
	"\rPreKeyRequest\x12.\n" +
	"\x13target_identity_key\x18\x01 \x01(\fR\x11targetIdentityKey\x12-\n" +
	"\x10target_device_id\x18\x02 \x01(\fH\x00R\x0etargetDeviceId\x88\x01\x01B\x13\n" +
	"\x11_target_device_id\"\xbe\x01\n" +
	"\x15SenderKeyDistribution\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12,\n" +
	"\x12sender_key_message\x18\x02 \x01(\fR\x10senderKeyMessage\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\rR\n" +
	"generation\x12.\n" +
	"\x13target_identity_key\x18\x04 \x01(\fR\x11targetIdentityKey*\xa5\x01\n" +
	"\vMessageType\x12\x15\n" +
	"\x11MESSAGE_TYPE_TEXT\x10\x00\x12\x16\n" +
	"\x12MESSAGE_TYPE_IMAGE\x10\x01\x12\x15\n" +
	"\x11MESSAGE_TYPE_FILE\x10\x02\x12\x1b\n" +
	"\x17MESSAGE_TYPE_VOICE_NOTE\x10\x03\x12\x1a\n" +
	"\x16MESSAGE_TYPE_VIEW_ONCE\x10\x04\x12\x17\n" +
	"\x13MESSAGE_TYPE_SYSTEM\x10\x05B.Z,github.com/AegisSec/veil-server/pkg/proto/v1b\x06proto3"

var (
	file_veil_v1_chat_proto_rawDescOnce sync.Once
	file_veil_v1_chat_proto_rawDescData []byte
)

func file_veil_v1_chat_proto_rawDescGZIP() []byte {
	file_veil_v1_chat_proto_rawDescOnce.Do(func() {
		file_veil_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_veil_v1_chat_proto_rawDesc), len(file_veil_v1_chat_proto_rawDesc)))
	})
	return file_veil_v1_chat_proto_rawDescData
}

var file_veil_v1_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_veil_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_veil_v1_chat_proto_goTypes = []any{
	(MessageType)(0),              // 0: veil.v1.MessageType
	(MessageEvent_EventType)(0),   // 1: veil.v1.MessageEvent.EventType
	(*SendMessage)(nil),           // 2: veil.v1.SendMessage
	(*EncryptedAttachment)(nil),   // 3: veil.v1.EncryptedAttachment
	(*MessageAck)(nil),            // 4: veil.v1.MessageAck
	(*MessageDelivered)(nil),      // 5: veil.v1.MessageDelivered
	(*MessageRead)(nil),           // 6: veil.v1.MessageRead
	(*EditMessage)(nil),           // 7: veil.v1.EditMessage
	(*DeleteMessage)(nil),         // 8: veil.v1.DeleteMessage
	(*MessageEvent)(nil),          // 9: veil.v1.MessageEvent
	(*PreKeyBundle)(nil),          // 10: veil.v1.PreKeyBundle
	(*PreKeyRequest)(nil),         // 11: veil.v1.PreKeyRequest
	(*SenderKeyDistribution)(nil), // 12: veil.v1.SenderKeyDistribution
}
var file_veil_v1_chat_proto_depIdxs = []int32{
	0, // 0: veil.v1.SendMessage.msg_type:type_name -> veil.v1.MessageType
	3, // 1: veil.v1.SendMessage.attachments:type_name -> veil.v1.EncryptedAttachment
	1, // 2: veil.v1.MessageEvent.event_type:type_name -> veil.v1.MessageEvent.EventType
	0, // 3: veil.v1.MessageEvent.msg_type:type_name -> veil.v1.MessageType
	3, // 4: veil.v1.MessageEvent.attachments:type_name -> veil.v1.EncryptedAttachment
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_veil_v1_chat_proto_init() }
func file_veil_v1_chat_proto_init() {
	if File_veil_v1_chat_proto != nil {
		return
	}
	file_veil_v1_chat_proto_msgTypes[0].OneofWrappers = []any{}
	file_veil_v1_chat_proto_msgTypes[7].OneofWrappers = []any{}
	file_veil_v1_chat_proto_msgTypes[8].OneofWrappers = []any{}
	file_veil_v1_chat_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_veil_v1_chat_proto_rawDesc), len(file_veil_v1_chat_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_veil_v1_chat_proto_goTypes,
		DependencyIndexes: file_veil_v1_chat_proto_depIdxs,
		EnumInfos:         file_veil_v1_chat_proto_enumTypes,
		MessageInfos:      file_veil_v1_chat_proto_msgTypes,
	}.Build()
	File_veil_v1_chat_proto = out.File
	file_veil_v1_chat_proto_goTypes = nil
	file_veil_v1_chat_proto_depIdxs = nil
}
