// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: veil/v1/envelope.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope — корневое сообщение для всех WebSocket фреймов.
// Клиент и сервер обмениваются исключительно Envelope.
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sequence number (клиент задаёт, сервер отвечает тем же для ACK)
	Seq uint64 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// Серверный timestamp (UTC, наносекунды с epoch)
	Timestamp uint64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_AuthChallenge
	//	*Envelope_AuthResponse
	//	*Envelope_AuthResult
	//	*Envelope_RegisterDevice
	//	*Envelope_SendMessage
	//	*Envelope_MessageAck
	//	*Envelope_MessageDelivered
	//	*Envelope_MessageRead
	//	*Envelope_EditMessage
	//	*Envelope_DeleteMessage
	//	*Envelope_MessageEvent
	//	*Envelope_ReactionUpdate
	//	*Envelope_ReactionEvent
	//	*Envelope_PrekeyBundle
	//	*Envelope_PrekeyRequest
	//	*Envelope_SenderKeyDist
	//	*Envelope_PresenceUpdate
	//	*Envelope_TypingEvent
	//	*Envelope_FriendRequest
	//	*Envelope_FriendRequestEvent
	//	*Envelope_FriendRespond
	//	*Envelope_FriendAcceptedEvent
	//	*Envelope_FriendRemove
	//	*Envelope_FriendRemovedEvent
	//	*Envelope_FriendListRequest
	//	*Envelope_FriendListResponse
	//	*Envelope_ServerEvent
	//	*Envelope_ChannelEvent
	//	*Envelope_ShareCreate
	//	*Envelope_ShareCreated
	//	*Envelope_MediaUploadRequest
	//	*Envelope_MediaUploadUrl
	//	*Envelope_VoiceTokenRequest
	//	*Envelope_VoiceToken
	//	*Envelope_SyncRequest
	//	*Envelope_SyncBatch
	//	*Envelope_Error
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_veil_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_veil_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Envelope) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetAuthChallenge() *AuthChallenge {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_AuthChallenge); ok {
			return x.AuthChallenge
		}
	}
	return nil
}

func (x *Envelope) GetAuthResponse() *AuthResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_AuthResponse); ok {
			return x.AuthResponse
		}
	}
	return nil
}

func (x *Envelope) GetAuthResult() *AuthResult {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_AuthResult); ok {
			return x.AuthResult
		}
	}
	return nil
}

func (x *Envelope) GetRegisterDevice() *RegisterDevice {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_RegisterDevice); ok {
			return x.RegisterDevice
		}
	}
	return nil
}

func (x *Envelope) GetSendMessage() *SendMessage {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SendMessage); ok {
			return x.SendMessage
		}
	}
	return nil
}

func (x *Envelope) GetMessageAck() *MessageAck {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_MessageAck); ok {
			return x.MessageAck
		}
	}
	return nil
}

func (x *Envelope) GetMessageDelivered() *MessageDelivered {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_MessageDelivered); ok {
			return x.MessageDelivered
		}
	}
	return nil
}

func (x *Envelope) GetMessageRead() *MessageRead {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_MessageRead); ok {
			return x.MessageRead
		}
	}
	return nil
}

func (x *Envelope) GetEditMessage() *EditMessage {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_EditMessage); ok {
			return x.EditMessage
		}
	}
	return nil
}

func (x *Envelope) GetDeleteMessage() *DeleteMessage {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_DeleteMessage); ok {
			return x.DeleteMessage
		}
	}
	return nil
}

func (x *Envelope) GetMessageEvent() *MessageEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_MessageEvent); ok {
			return x.MessageEvent
		}
	}
	return nil
}

func (x *Envelope) GetReactionUpdate() *ReactionUpdate {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ReactionUpdate); ok {
			return x.ReactionUpdate
		}
	}
	return nil
}

func (x *Envelope) GetReactionEvent() *ReactionEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ReactionEvent); ok {
			return x.ReactionEvent
		}
	}
	return nil
}

func (x *Envelope) GetPrekeyBundle() *PreKeyBundle {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_PrekeyBundle); ok {
			return x.PrekeyBundle
		}
	}
	return nil
}

func (x *Envelope) GetPrekeyRequest() *PreKeyRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_PrekeyRequest); ok {
			return x.PrekeyRequest
		}
	}
	return nil
}

func (x *Envelope) GetSenderKeyDist() *SenderKeyDistribution {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SenderKeyDist); ok {
			return x.SenderKeyDist
		}
	}
	return nil
}

func (x *Envelope) GetPresenceUpdate() *PresenceUpdate {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_PresenceUpdate); ok {
			return x.PresenceUpdate
		}
	}
	return nil
}

func (x *Envelope) GetTypingEvent() *TypingEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_TypingEvent); ok {
			return x.TypingEvent
		}
	}
	return nil
}

func (x *Envelope) GetFriendRequest() *FriendRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_FriendRequest); ok {
			return x.FriendRequest
		}
	}
	return nil
}

func (x *Envelope) GetFriendRequestEvent() *FriendRequestEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_FriendRequestEvent); ok {
			return x.FriendRequestEvent
		}
	}
	return nil
}

func (x *Envelope) GetFriendRespond() *FriendRespond {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_FriendRespond); ok {
			return x.FriendRespond
		}
	}
	return nil
}

func (x *Envelope) GetFriendAcceptedEvent() *FriendAcceptedEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_FriendAcceptedEvent); ok {
			return x.FriendAcceptedEvent
		}
	}
	return nil
}

func (x *Envelope) GetFriendRemove() *FriendRemove {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_FriendRemove); ok {
			return x.FriendRemove
		}
	}
	return nil
}

func (x *Envelope) GetFriendRemovedEvent() *FriendRemovedEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_FriendRemovedEvent); ok {
			return x.FriendRemovedEvent
		}
	}
	return nil
}

func (x *Envelope) GetFriendListRequest() *FriendListRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_FriendListRequest); ok {
			return x.FriendListRequest
		}
	}
	return nil
}

func (x *Envelope) GetFriendListResponse() *FriendListResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_FriendListResponse); ok {
			return x.FriendListResponse
		}
	}
	return nil
}

func (x *Envelope) GetServerEvent() *ServerEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ServerEvent); ok {
			return x.ServerEvent
		}
	}
	return nil
}

func (x *Envelope) GetChannelEvent() *ChannelEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ChannelEvent); ok {
			return x.ChannelEvent
		}
	}
	return nil
}

func (x *Envelope) GetShareCreate() *ShareCreate {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ShareCreate); ok {
			return x.ShareCreate
		}
	}
	return nil
}

func (x *Envelope) GetShareCreated() *ShareCreated {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ShareCreated); ok {
			return x.ShareCreated
		}
	}
	return nil
}

func (x *Envelope) GetMediaUploadRequest() *MediaUploadRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_MediaUploadRequest); ok {
			return x.MediaUploadRequest
		}
	}
	return nil
}

func (x *Envelope) GetMediaUploadUrl() *MediaUploadUrl {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_MediaUploadUrl); ok {
			return x.MediaUploadUrl
		}
	}
	return nil
}

func (x *Envelope) GetVoiceTokenRequest() *VoiceTokenRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_VoiceTokenRequest); ok {
			return x.VoiceTokenRequest
		}
	}
	return nil
}

func (x *Envelope) GetVoiceToken() *VoiceToken {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_VoiceToken); ok {
			return x.VoiceToken
		}
	}
	return nil
}

func (x *Envelope) GetSyncRequest() *SyncRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SyncRequest); ok {
			return x.SyncRequest
		}
	}
	return nil
}

func (x *Envelope) GetSyncBatch() *SyncBatch {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_SyncBatch); ok {
			return x.SyncBatch
		}
	}
	return nil
}

func (x *Envelope) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_AuthChallenge struct {
	// Auth
	AuthChallenge *AuthChallenge `protobuf:"bytes,10,opt,name=auth_challenge,json=authChallenge,proto3,oneof"`
}

type Envelope_AuthResponse struct {
	AuthResponse *AuthResponse `protobuf:"bytes,11,opt,name=auth_response,json=authResponse,proto3,oneof"`
}

type Envelope_AuthResult struct {
	AuthResult *AuthResult `protobuf:"bytes,12,opt,name=auth_result,json=authResult,proto3,oneof"`
}

type Envelope_RegisterDevice struct {
	RegisterDevice *RegisterDevice `protobuf:"bytes,13,opt,name=register_device,json=registerDevice,proto3,oneof"`
}

type Envelope_SendMessage struct {
	// Chat
	SendMessage *SendMessage `protobuf:"bytes,20,opt,name=send_message,json=sendMessage,proto3,oneof"`
}

type Envelope_MessageAck struct {
	MessageAck *MessageAck `protobuf:"bytes,21,opt,name=message_ack,json=messageAck,proto3,oneof"`
}

type Envelope_MessageDelivered struct {
	MessageDelivered *MessageDelivered `protobuf:"bytes,22,opt,name=message_delivered,json=messageDelivered,proto3,oneof"`
}

type Envelope_MessageRead struct {
	MessageRead *MessageRead `protobuf:"bytes,23,opt,name=message_read,json=messageRead,proto3,oneof"`
}

type Envelope_EditMessage struct {
	EditMessage *EditMessage `protobuf:"bytes,24,opt,name=edit_message,json=editMessage,proto3,oneof"`
}

type Envelope_DeleteMessage struct {
	DeleteMessage *DeleteMessage `protobuf:"bytes,25,opt,name=delete_message,json=deleteMessage,proto3,oneof"`
}

type Envelope_MessageEvent struct {
	MessageEvent *MessageEvent `protobuf:"bytes,26,opt,name=message_event,json=messageEvent,proto3,oneof"`
}

type Envelope_ReactionUpdate struct {
	ReactionUpdate *ReactionUpdate `protobuf:"bytes,27,opt,name=reaction_update,json=reactionUpdate,proto3,oneof"`
}

type Envelope_ReactionEvent struct {
	ReactionEvent *ReactionEvent `protobuf:"bytes,28,opt,name=reaction_event,json=reactionEvent,proto3,oneof"`
}

type Envelope_PrekeyBundle struct {
	// Crypto key exchange
	PrekeyBundle *PreKeyBundle `protobuf:"bytes,30,opt,name=prekey_bundle,json=prekeyBundle,proto3,oneof"`
}

type Envelope_PrekeyRequest struct {
	PrekeyRequest *PreKeyRequest `protobuf:"bytes,31,opt,name=prekey_request,json=prekeyRequest,proto3,oneof"`
}

type Envelope_SenderKeyDist struct {
	SenderKeyDist *SenderKeyDistribution `protobuf:"bytes,32,opt,name=sender_key_dist,json=senderKeyDist,proto3,oneof"`
}

type Envelope_PresenceUpdate struct {
	// Presence
	PresenceUpdate *PresenceUpdate `protobuf:"bytes,40,opt,name=presence_update,json=presenceUpdate,proto3,oneof"`
}

type Envelope_TypingEvent struct {
	TypingEvent *TypingEvent `protobuf:"bytes,41,opt,name=typing_event,json=typingEvent,proto3,oneof"`
}

type Envelope_FriendRequest struct {
	// Friends
	FriendRequest *FriendRequest `protobuf:"bytes,42,opt,name=friend_request,json=friendRequest,proto3,oneof"`
}

type Envelope_FriendRequestEvent struct {
	FriendRequestEvent *FriendRequestEvent `protobuf:"bytes,43,opt,name=friend_request_event,json=friendRequestEvent,proto3,oneof"`
}

type Envelope_FriendRespond struct {
	FriendRespond *FriendRespond `protobuf:"bytes,44,opt,name=friend_respond,json=friendRespond,proto3,oneof"`
}

type Envelope_FriendAcceptedEvent struct {
	FriendAcceptedEvent *FriendAcceptedEvent `protobuf:"bytes,45,opt,name=friend_accepted_event,json=friendAcceptedEvent,proto3,oneof"`
}

type Envelope_FriendRemove struct {
	FriendRemove *FriendRemove `protobuf:"bytes,46,opt,name=friend_remove,json=friendRemove,proto3,oneof"`
}

type Envelope_FriendRemovedEvent struct {
	FriendRemovedEvent *FriendRemovedEvent `protobuf:"bytes,47,opt,name=friend_removed_event,json=friendRemovedEvent,proto3,oneof"`
}

type Envelope_FriendListRequest struct {
	FriendListRequest *FriendListRequest `protobuf:"bytes,48,opt,name=friend_list_request,json=friendListRequest,proto3,oneof"`
}

type Envelope_FriendListResponse struct {
	FriendListResponse *FriendListResponse `protobuf:"bytes,49,opt,name=friend_list_response,json=friendListResponse,proto3,oneof"`
}

type Envelope_ServerEvent struct {
	// Servers & Channels
	ServerEvent *ServerEvent `protobuf:"bytes,50,opt,name=server_event,json=serverEvent,proto3,oneof"`
}

type Envelope_ChannelEvent struct {
	ChannelEvent *ChannelEvent `protobuf:"bytes,51,opt,name=channel_event,json=channelEvent,proto3,oneof"`
}

type Envelope_ShareCreate struct {
	// Shares
	ShareCreate *ShareCreate `protobuf:"bytes,60,opt,name=share_create,json=shareCreate,proto3,oneof"`
}

type Envelope_ShareCreated struct {
	ShareCreated *ShareCreated `protobuf:"bytes,61,opt,name=share_created,json=shareCreated,proto3,oneof"`
}

type Envelope_MediaUploadRequest struct {
	// Media
	MediaUploadRequest *MediaUploadRequest `protobuf:"bytes,70,opt,name=media_upload_request,json=mediaUploadRequest,proto3,oneof"`
}

type Envelope_MediaUploadUrl struct {
	MediaUploadUrl *MediaUploadUrl `protobuf:"bytes,71,opt,name=media_upload_url,json=mediaUploadUrl,proto3,oneof"`
}

type Envelope_VoiceTokenRequest struct {
	// Voice
	VoiceTokenRequest *VoiceTokenRequest `protobuf:"bytes,80,opt,name=voice_token_request,json=voiceTokenRequest,proto3,oneof"`
}

type Envelope_VoiceToken struct {
	VoiceToken *VoiceToken `protobuf:"bytes,81,opt,name=voice_token,json=voiceToken,proto3,oneof"`
}

type Envelope_SyncRequest struct {
	// Sync (multi-device)
	SyncRequest *SyncRequest `protobuf:"bytes,90,opt,name=sync_request,json=syncRequest,proto3,oneof"`
}

type Envelope_SyncBatch struct {
	SyncBatch *SyncBatch `protobuf:"bytes,91,opt,name=sync_batch,json=syncBatch,proto3,oneof"`
}

type Envelope_Error struct {
	// Error
	Error *Error `protobuf:"bytes,100,opt,name=error,proto3,oneof"`
}

func (*Envelope_AuthChallenge) isEnvelope_Payload() {}

func (*Envelope_AuthResponse) isEnvelope_Payload() {}

func (*Envelope_AuthResult) isEnvelope_Payload() {}

func (*Envelope_RegisterDevice) isEnvelope_Payload() {}

func (*Envelope_SendMessage) isEnvelope_Payload() {}

func (*Envelope_MessageAck) isEnvelope_Payload() {}

func (*Envelope_MessageDelivered) isEnvelope_Payload() {}

func (*Envelope_MessageRead) isEnvelope_Payload() {}

func (*Envelope_EditMessage) isEnvelope_Payload() {}

func (*Envelope_DeleteMessage) isEnvelope_Payload() {}

func (*Envelope_MessageEvent) isEnvelope_Payload() {}

func (*Envelope_ReactionUpdate) isEnvelope_Payload() {}

func (*Envelope_ReactionEvent) isEnvelope_Payload() {}

func (*Envelope_PrekeyBundle) isEnvelope_Payload() {}

func (*Envelope_PrekeyRequest) isEnvelope_Payload() {}

func (*Envelope_SenderKeyDist) isEnvelope_Payload() {}

func (*Envelope_PresenceUpdate) isEnvelope_Payload() {}

func (*Envelope_TypingEvent) isEnvelope_Payload() {}

func (*Envelope_FriendRequest) isEnvelope_Payload() {}

func (*Envelope_FriendRequestEvent) isEnvelope_Payload() {}

func (*Envelope_FriendRespond) isEnvelope_Payload() {}

func (*Envelope_FriendAcceptedEvent) isEnvelope_Payload() {}

func (*Envelope_FriendRemove) isEnvelope_Payload() {}

func (*Envelope_FriendRemovedEvent) isEnvelope_Payload() {}

func (*Envelope_FriendListRequest) isEnvelope_Payload() {}

func (*Envelope_FriendListResponse) isEnvelope_Payload() {}

func (*Envelope_ServerEvent) isEnvelope_Payload() {}

func (*Envelope_ChannelEvent) isEnvelope_Payload() {}

func (*Envelope_ShareCreate) isEnvelope_Payload() {}

func (*Envelope_ShareCreated) isEnvelope_Payload() {}

func (*Envelope_MediaUploadRequest) isEnvelope_Payload() {}

func (*Envelope_MediaUploadUrl) isEnvelope_Payload() {}

func (*Envelope_VoiceTokenRequest) isEnvelope_Payload() {}

func (*Envelope_VoiceToken) isEnvelope_Payload() {}

func (*Envelope_SyncRequest) isEnvelope_Payload() {}

func (*Envelope_SyncBatch) isEnvelope_Payload() {}

func (*Envelope_Error) isEnvelope_Payload() {}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RefSeq        *uint64                `protobuf:"varint,3,opt,name=ref_seq,json=refSeq,proto3,oneof" json:"ref_seq,omitempty"` // Ссылка на seq запроса, вызвавшего ошибку
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_veil_v1_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_veil_v1_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetRefSeq() uint64 {
	if x != nil && x.RefSeq != nil {
		return *x.RefSeq
	}
	return 0
}

var File_veil_v1_envelope_proto protoreflect.FileDescriptor

const file_veil_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"\x16veil/v1/envelope.proto\x12\aveil.v1\x1a\x12veil/v1/auth.proto\x1a\x12veil/v1/chat.proto\x1a\x16veil/v1/presence.proto\x1a\x13veil/v1/share.proto\x1a\x14veil/v1/server.proto\x1a\x13veil/v1/media.proto\x1a\x13veil/v1/voice.proto\x1a\x15veil/v1/friends.proto\"\xba\x13\n" +
	"\bEnvelope\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12?\n" +
	"\x0eauth_challenge\x18\n" +
	" \x01(\v2\x16.veil.v1.AuthChallengeH\x00R\rauthChallenge\x12<\n" +
	"\rauth_response\x18\v \x01(\v2\x15.veil.v1.AuthResponseH\x00R\fauthResponse\x126\n" +
	"\vauth_result\x18\f \x01(\v2\x13.veil.v1.AuthResultH\x00R\n" +
	"authResult\x12B\n" +
	"\x0fregister_device\x18\r \x01(\v2\x17.veil.v1.RegisterDeviceH\x00R\x0eregisterDevice\x129\n" +
	"\fsend_message\x18\x14 \x01(\v2\x14.veil.v1.SendMessageH\x00R\vsendMessage\x126\n" +
	"\vmessage_ack\x18\x15 \x01(\v2\x13.veil.v1.MessageAckH\x00R\n" +
	"messageAck\x12H\n" +
	"\x11message_delivered\x18\x16 \x01(\v2\x19.veil.v1.MessageDeliveredH\x00R\x10messageDelivered\x129\n" +
	"\fmessage_read\x18\x17 \x01(\v2\x14.veil.v1.MessageReadH\x00R\vmessageRead\x129\n" +
	"\fedit_message\x18\x18 \x01(\v2\x14.veil.v1.EditMessageH\x00R\veditMessage\x12?\n" +
	"\x0edelete_message\x18\x19 \x01(\v2\x16.veil.v1.DeleteMessageH\x00R\rdeleteMessage\x12<\n" +
	"\rmessage_event\x18\x1a \x01(\v2\x15.veil.v1.MessageEventH\x00R\fmessageEvent\x12B\n" +
	"\x0freaction_update\x18\x1b \x01(\v2\x17.veil.v1.ReactionUpdateH\x00R\x0ereactionUpdate\x12?\n" +
	"\x0ereaction_event\x18\x1c \x01(\v2\x16.veil.v1.ReactionEventH\x00R\rreactionEvent\x12<\n" +
	"\rprekey_bundle\x18\x1e \x01(\v2\x15.veil.v1.PreKeyBundleH\x00R\fprekeyBundle\x12?\n" +
	"\x0eprekey_request\x18\x1f \x01(\v2\x16.veil.v1.PreKeyRequestH\x00R\rprekeyRequest\x12H\n" +
	"\x0fsender_key_dist\x18  \x01(\v2\x1e.veil.v1.SenderKeyDistributionH\x00R\rsenderKeyDist\x12B\n" +
	"\x0fpresence_update\x18( \x01(\v2\x17.veil.v1.PresenceUpdateH\x00R\x0epresenceUpdate\x129\n" +
	"\ftyping_event\x18) \x01(\v2\x14.veil.v1.TypingEventH\x00R\vtypingEvent\x12?\n" +
	"\x0efriend_request\x18* \x01(\v2\x16.veil.v1.FriendRequestH\x00R\rfriendRequest\x12O\n" +
	"\x14friend_request_event\x18+ \x01(\v2\x1b.veil.v1.FriendRequestEventH\x00R\x12friendRequestEvent\x12?\n" +
	"\x0efriend_respond\x18, \x01(\v2\x16.veil.v1.FriendRespondH\x00R\rfriendRespond\x12R\n" +
	"\x15friend_accepted_event\x18- \x01(\v2\x1c.veil.v1.FriendAcceptedEventH\x00R\x13friendAcceptedEvent\x12<\n" +
	"\rfriend_remove\x18. \x01(\v2\x15.veil.v1.FriendRemoveH\x00R\ffriendRemove\x12O\n" +
	"\x14friend_removed_event\x18/ \x01(\v2\x1b.veil.v1.FriendRemovedEventH\x00R\x12friendRemovedEvent\x12L\n" +
	"\x13friend_list_request\x180 \x01(\v2\x1a.veil.v1.FriendListRequestH\x00R\x11friendListRequest\x12O\n" +
	"\x14friend_list_response\x181 \x01(\v2\x1b.veil.v1.FriendListResponseH\x00R\x12friendListResponse\x129\n" +
	"\fserver_event\x182 \x01(\v2\x14.veil.v1.ServerEventH\x00R\vserverEvent\x12<\n" +
	"\rchannel_event\x183 \x01(\v2\x15.veil.v1.ChannelEventH\x00R\fchannelEvent\x129\n" +
	"\fshare_create\x18< \x01(\v2\x14.veil.v1.ShareCreateH\x00R\vshareCreate\x12<\n" +
	"\rshare_created\x18= \x01(\v2\x15.veil.v1.ShareCreatedH\x00R\fshareCreated\x12O\n" +
	"\x14media_upload_request\x18F \x01(\v2\x1b.veil.v1.MediaUploadRequestH\x00R\x12mediaUploadRequest\x12C\n" +
	"\x10media_upload_url\x18G \x01(\v2\x17.veil.v1.MediaUploadUrlH\x00R\x0emediaUploadUrl\x12L\n" +
	"\x13voice_token_request\x18P \x01(\v2\x1a.veil.v1.VoiceTokenRequestH\x00R\x11voiceTokenRequest\x126\n" +
	"\vvoice_token\x18Q \x01(\v2\x13.veil.v1.VoiceTokenH\x00R\n" +
	"voiceToken\x129\n" +
	"\fsync_request\x18Z \x01(\v2\x14.veil.v1.SyncRequestH\x00R\vsyncRequest\x123\n" +
	"\n" +
	"sync_batch\x18[ \x01(\v2\x12.veil.v1.SyncBatchH\x00R\tsyncBatch\x12&\n" +
	"\x05error\x18d \x01(\v2\x0e.veil.v1.ErrorH\x00R\x05errorB\t\n" +
	"\apayload\"_\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\aref_seq\x18\x03 \x01(\x04H\x00R\x06refSeq\x88\x01\x01B\n" +
	"\n" +
	"\b_ref_seqB.Z,github.com/AegisSec/veil-server/pkg/proto/v1b\x06proto3"

var (
	file_veil_v1_envelope_proto_rawDescOnce sync.Once
	file_veil_v1_envelope_proto_rawDescData []byte
)

func file_veil_v1_envelope_proto_rawDescGZIP() []byte {
	file_veil_v1_envelope_proto_rawDescOnce.Do(func() {
		file_veil_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_veil_v1_envelope_proto_rawDesc), len(file_veil_v1_envelope_proto_rawDesc)))
	})
	return file_veil_v1_envelope_proto_rawDescData
}

var file_veil_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_veil_v1_envelope_proto_goTypes = []any{
	(*Envelope)(nil),              // 0: veil.v1.Envelope
	(*Error)(nil),                 // 1: veil.v1.Error
	(*AuthChallenge)(nil),         // 2: veil.v1.AuthChallenge
	(*AuthResponse)(nil),          // 3: veil.v1.AuthResponse
	(*AuthResult)(nil),            // 4: veil.v1.AuthResult
	(*RegisterDevice)(nil),        // 5: veil.v1.RegisterDevice
	(*SendMessage)(nil),           // 6: veil.v1.SendMessage
	(*MessageAck)(nil),            // 7: veil.v1.MessageAck
	(*MessageDelivered)(nil),      // 8: veil.v1.MessageDelivered
	(*MessageRead)(nil),           // 9: veil.v1.MessageRead
	(*EditMessage)(nil),           // 10: veil.v1.EditMessage
	(*DeleteMessage)(nil),         // 11: veil.v1.DeleteMessage
	(*MessageEvent)(nil),          // 12: veil.v1.MessageEvent
	(*ReactionUpdate)(nil),        // 13: veil.v1.ReactionUpdate
	(*ReactionEvent)(nil),         // 14: veil.v1.ReactionEvent
	(*PreKeyBundle)(nil),          // 15: veil.v1.PreKeyBundle
	(*PreKeyRequest)(nil),         // 16: veil.v1.PreKeyRequest
	(*SenderKeyDistribution)(nil), // 17: veil.v1.SenderKeyDistribution
	(*PresenceUpdate)(nil),        // 18: veil.v1.PresenceUpdate
	(*TypingEvent)(nil),           // 19: veil.v1.TypingEvent
	(*FriendRequest)(nil),         // 20: veil.v1.FriendRequest
	(*FriendRequestEvent)(nil),    // 21: veil.v1.FriendRequestEvent
	(*FriendRespond)(nil),         // 22: veil.v1.FriendRespond
	(*FriendAcceptedEvent)(nil),   // 23: veil.v1.FriendAcceptedEvent
	(*FriendRemove)(nil),          // 24: veil.v1.FriendRemove
	(*FriendRemovedEvent)(nil),    // 25: veil.v1.FriendRemovedEvent
	(*FriendListRequest)(nil),     // 26: veil.v1.FriendListRequest
	(*FriendListResponse)(nil),    // 27: veil.v1.FriendListResponse
	(*ServerEvent)(nil),           // 28: veil.v1.ServerEvent
	(*ChannelEvent)(nil),          // 29: veil.v1.ChannelEvent
	(*ShareCreate)(nil),           // 30: veil.v1.ShareCreate
	(*ShareCreated)(nil),          // 31: veil.v1.ShareCreated
	(*MediaUploadRequest)(nil),    // 32: veil.v1.MediaUploadRequest
	(*MediaUploadUrl)(nil),        // 33: veil.v1.MediaUploadUrl
	(*VoiceTokenRequest)(nil),     // 34: veil.v1.VoiceTokenRequest
	(*VoiceToken)(nil),            // 35: veil.v1.VoiceToken
	(*SyncRequest)(nil),           // 36: veil.v1.SyncRequest
	(*SyncBatch)(nil),             // 37: veil.v1.SyncBatch
}
var file_veil_v1_envelope_proto_depIdxs = []int32{
	2,  // 0: veil.v1.Envelope.auth_challenge:type_name -> veil.v1.AuthChallenge
	3,  // 1: veil.v1.Envelope.auth_response:type_name -> veil.v1.AuthResponse
	4,  // 2: veil.v1.Envelope.auth_result:type_name -> veil.v1.AuthResult
	5,  // 3: veil.v1.Envelope.register_device:type_name -> veil.v1.RegisterDevice
	6,  // 4: veil.v1.Envelope.send_message:type_name -> veil.v1.SendMessage
	7,  // 5: veil.v1.Envelope.message_ack:type_name -> veil.v1.MessageAck
	8,  // 6: veil.v1.Envelope.message_delivered:type_name -> veil.v1.MessageDelivered
	9,  // 7: veil.v1.Envelope.message_read:type_name -> veil.v1.MessageRead
	10, // 8: veil.v1.Envelope.edit_message:type_name -> veil.v1.EditMessage
	11, // 9: veil.v1.Envelope.delete_message:type_name -> veil.v1.DeleteMessage
	12, // 10: veil.v1.Envelope.message_event:type_name -> veil.v1.MessageEvent
	13, // 11: veil.v1.Envelope.reaction_update:type_name -> veil.v1.ReactionUpdate
	14, // 12: veil.v1.Envelope.reaction_event:type_name -> veil.v1.ReactionEvent
	15, // 13: veil.v1.Envelope.prekey_bundle:type_name -> veil.v1.PreKeyBundle
	16, // 14: veil.v1.Envelope.prekey_request:type_name -> veil.v1.PreKeyRequest
	17, // 15: veil.v1.Envelope.sender_key_dist:type_name -> veil.v1.SenderKeyDistribution
	18, // 16: veil.v1.Envelope.presence_update:type_name -> veil.v1.PresenceUpdate
	19, // 17: veil.v1.Envelope.typing_event:type_name -> veil.v1.TypingEvent
	20, // 18: veil.v1.Envelope.friend_request:type_name -> veil.v1.FriendRequest
	21, // 19: veil.v1.Envelope.friend_request_event:type_name -> veil.v1.FriendRequestEvent
	22, // 20: veil.v1.Envelope.friend_respond:type_name -> veil.v1.FriendRespond
	23, // 21: veil.v1.Envelope.friend_accepted_event:type_name -> veil.v1.FriendAcceptedEvent
	24, // 22: veil.v1.Envelope.friend_remove:type_name -> veil.v1.FriendRemove
	25, // 23: veil.v1.Envelope.friend_removed_event:type_name -> veil.v1.FriendRemovedEvent
	26, // 24: veil.v1.Envelope.friend_list_request:type_name -> veil.v1.FriendListRequest
	27, // 25: veil.v1.Envelope.friend_list_response:type_name -> veil.v1.FriendListResponse
	28, // 26: veil.v1.Envelope.server_event:type_name -> veil.v1.ServerEvent
	29, // 27: veil.v1.Envelope.channel_event:type_name -> veil.v1.ChannelEvent
	30, // 28: veil.v1.Envelope.share_create:type_name -> veil.v1.ShareCreate
	31, // 29: veil.v1.Envelope.share_created:type_name -> veil.v1.ShareCreated
	32, // 30: veil.v1.Envelope.media_upload_request:type_name -> veil.v1.MediaUploadRequest
	33, // 31: veil.v1.Envelope.media_upload_url:type_name -> veil.v1.MediaUploadUrl
	34, // 32: veil.v1.Envelope.voice_token_request:type_name -> veil.v1.VoiceTokenRequest
	35, // 33: veil.v1.Envelope.voice_token:type_name -> veil.v1.VoiceToken
	36, // 34: veil.v1.Envelope.sync_request:type_name -> veil.v1.SyncRequest
	37, // 35: veil.v1.Envelope.sync_batch:type_name -> veil.v1.SyncBatch
	1,  // 36: veil.v1.Envelope.error:type_name -> veil.v1.Error
	37, // [37:37] is the sub-list for method output_type
	37, // [37:37] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_veil_v1_envelope_proto_init() }
func file_veil_v1_envelope_proto_init() {
	if File_veil_v1_envelope_proto != nil {
		return
	}
	file_veil_v1_auth_proto_init()
	file_veil_v1_chat_proto_init()
	file_veil_v1_presence_proto_init()
	file_veil_v1_share_proto_init()
	file_veil_v1_server_proto_init()
	file_veil_v1_media_proto_init()
	file_veil_v1_voice_proto_init()
	file_veil_v1_friends_proto_init()
	file_veil_v1_envelope_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_AuthChallenge)(nil),
		(*Envelope_AuthResponse)(nil),
		(*Envelope_AuthResult)(nil),
		(*Envelope_RegisterDevice)(nil),
		(*Envelope_SendMessage)(nil),
		(*Envelope_MessageAck)(nil),
		(*Envelope_MessageDelivered)(nil),
		(*Envelope_MessageRead)(nil),
		(*Envelope_EditMessage)(nil),
		(*Envelope_DeleteMessage)(nil),
		(*Envelope_MessageEvent)(nil),
		(*Envelope_ReactionUpdate)(nil),
		(*Envelope_ReactionEvent)(nil),
		(*Envelope_PrekeyBundle)(nil),
		(*Envelope_PrekeyRequest)(nil),
		(*Envelope_SenderKeyDist)(nil),
		(*Envelope_PresenceUpdate)(nil),
		(*Envelope_TypingEvent)(nil),
		(*Envelope_FriendRequest)(nil),
		(*Envelope_FriendRequestEvent)(nil),
		(*Envelope_FriendRespond)(nil),
		(*Envelope_FriendAcceptedEvent)(nil),
		(*Envelope_FriendRemove)(nil),
		(*Envelope_FriendRemovedEvent)(nil),
		(*Envelope_FriendListRequest)(nil),
		(*Envelope_FriendListResponse)(nil),
		(*Envelope_ServerEvent)(nil),
		(*Envelope_ChannelEvent)(nil),
		(*Envelope_ShareCreate)(nil),
		(*Envelope_ShareCreated)(nil),
		(*Envelope_MediaUploadRequest)(nil),
		(*Envelope_MediaUploadUrl)(nil),
		(*Envelope_VoiceTokenRequest)(nil),
		(*Envelope_VoiceToken)(nil),
		(*Envelope_SyncRequest)(nil),
		(*Envelope_SyncBatch)(nil),
		(*Envelope_Error)(nil),
	}
	file_veil_v1_envelope_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_veil_v1_envelope_proto_rawDesc), len(file_veil_v1_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_veil_v1_envelope_proto_goTypes,
		DependencyIndexes: file_veil_v1_envelope_proto_depIdxs,
		MessageInfos:      file_veil_v1_envelope_proto_msgTypes,
	}.Build()
	File_veil_v1_envelope_proto = out.File
	file_veil_v1_envelope_proto_goTypes = nil
	file_veil_v1_envelope_proto_depIdxs = nil
}
