// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: veil/v1/friends.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Client → Server: send a friend request to another user
type FriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetUserId  string                 `protobuf:"bytes,1,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"` // User ID to send request to
	Message       *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`                           // Optional intro message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequest) Reset() {
	*x = FriendRequest{}
	mi := &file_veil_v1_friends_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequest) ProtoMessage() {}

func (x *FriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_friends_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequest.ProtoReflect.Descriptor instead.
func (*FriendRequest) Descriptor() ([]byte, []int) {
	return file_veil_v1_friends_proto_rawDescGZIP(), []int{0}
}

func (x *FriendRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *FriendRequest) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

// Server → Client: incoming friend request notification
type FriendRequestEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	FromUserId    string                 `protobuf:"bytes,2,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	FromUsername  string                 `protobuf:"bytes,3,opt,name=from_username,json=fromUsername,proto3" json:"from_username,omitempty"`
	Message       *string                `protobuf:"bytes,4,opt,name=message,proto3,oneof" json:"message,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequestEvent) Reset() {
	*x = FriendRequestEvent{}
	mi := &file_veil_v1_friends_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequestEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequestEvent) ProtoMessage() {}

func (x *FriendRequestEvent) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_friends_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequestEvent.ProtoReflect.Descriptor instead.
func (*FriendRequestEvent) Descriptor() ([]byte, []int) {
	return file_veil_v1_friends_proto_rawDescGZIP(), []int{1}
}

func (x *FriendRequestEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FriendRequestEvent) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *FriendRequestEvent) GetFromUsername() string {
	if x != nil {
		return x.FromUsername
	}
	return ""
}

func (x *FriendRequestEvent) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *FriendRequestEvent) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Client → Server: accept or reject a friend request
type FriendRespond struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Accept        bool                   `protobuf:"varint,2,opt,name=accept,proto3" json:"accept,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRespond) Reset() {
	*x = FriendRespond{}
	mi := &file_veil_v1_friends_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRespond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRespond) ProtoMessage() {}

func (x *FriendRespond) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_friends_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRespond.ProtoReflect.Descriptor instead.
func (*FriendRespond) Descriptor() ([]byte, []int) {
	return file_veil_v1_friends_proto_rawDescGZIP(), []int{2}
}

func (x *FriendRespond) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FriendRespond) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

// Server → Client: friend request was accepted (both users get this)
type FriendAcceptedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendAcceptedEvent) Reset() {
	*x = FriendAcceptedEvent{}
	mi := &file_veil_v1_friends_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendAcceptedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendAcceptedEvent) ProtoMessage() {}

func (x *FriendAcceptedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_friends_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendAcceptedEvent.ProtoReflect.Descriptor instead.
func (*FriendAcceptedEvent) Descriptor() ([]byte, []int) {
	return file_veil_v1_friends_proto_rawDescGZIP(), []int{3}
}

func (x *FriendAcceptedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FriendAcceptedEvent) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// Client → Server: remove a friend
type FriendRemove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRemove) Reset() {
	*x = FriendRemove{}
	mi := &file_veil_v1_friends_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRemove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRemove) ProtoMessage() {}

func (x *FriendRemove) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_friends_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRemove.ProtoReflect.Descriptor instead.
func (*FriendRemove) Descriptor() ([]byte, []int) {
	return file_veil_v1_friends_proto_rawDescGZIP(), []int{4}
}

func (x *FriendRemove) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Server → Client: you've been removed as a friend (also sent on remove)
type FriendRemovedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRemovedEvent) Reset() {
	*x = FriendRemovedEvent{}
	mi := &file_veil_v1_friends_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRemovedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRemovedEvent) ProtoMessage() {}

func (x *FriendRemovedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_friends_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRemovedEvent.ProtoReflect.Descriptor instead.
func (*FriendRemovedEvent) Descriptor() ([]byte, []int) {
	return file_veil_v1_friends_proto_rawDescGZIP(), []int{5}
}

func (x *FriendRemovedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Client → Server: request my friend list
type FriendListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendListRequest) Reset() {
	*x = FriendListRequest{}
	mi := &file_veil_v1_friends_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendListRequest) ProtoMessage() {}

func (x *FriendListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_friends_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendListRequest.ProtoReflect.Descriptor instead.
func (*FriendListRequest) Descriptor() ([]byte, []int) {
	return file_veil_v1_friends_proto_rawDescGZIP(), []int{6}
}

// Server → Client: full friend list response
type FriendListResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Friends         []*FriendEntry         `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	PendingRequests []*FriendRequestEntry  `protobuf:"bytes,2,rep,name=pending_requests,json=pendingRequests,proto3" json:"pending_requests,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FriendListResponse) Reset() {
	*x = FriendListResponse{}
	mi := &file_veil_v1_friends_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendListResponse) ProtoMessage() {}

func (x *FriendListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_friends_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendListResponse.ProtoReflect.Descriptor instead.
func (*FriendListResponse) Descriptor() ([]byte, []int) {
	return file_veil_v1_friends_proto_rawDescGZIP(), []int{7}
}

func (x *FriendListResponse) GetFriends() []*FriendEntry {
	if x != nil {
		return x.Friends
	}
	return nil
}

func (x *FriendListResponse) GetPendingRequests() []*FriendRequestEntry {
	if x != nil {
		return x.PendingRequests
	}
	return nil
}

type FriendEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Status        PresenceStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=veil.v1.PresenceStatus" json:"status,omitempty"` // Current online status
	LastSeen      *uint64                `protobuf:"varint,4,opt,name=last_seen,json=lastSeen,proto3,oneof" json:"last_seen,omitempty"`   // Timestamp of last presence
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendEntry) Reset() {
	*x = FriendEntry{}
	mi := &file_veil_v1_friends_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendEntry) ProtoMessage() {}

func (x *FriendEntry) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_friends_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendEntry.ProtoReflect.Descriptor instead.
func (*FriendEntry) Descriptor() ([]byte, []int) {
	return file_veil_v1_friends_proto_rawDescGZIP(), []int{8}
}

func (x *FriendEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FriendEntry) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *FriendEntry) GetStatus() PresenceStatus {
	if x != nil {
		return x.Status
	}
	return PresenceStatus_PRESENCE_UNKNOWN
}

func (x *FriendEntry) GetLastSeen() uint64 {
	if x != nil && x.LastSeen != nil {
		return *x.LastSeen
	}
	return 0
}

type FriendRequestEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	FromUserId    string                 `protobuf:"bytes,2,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	FromUsername  string                 `protobuf:"bytes,3,opt,name=from_username,json=fromUsername,proto3" json:"from_username,omitempty"`
	Message       *string                `protobuf:"bytes,4,opt,name=message,proto3,oneof" json:"message,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Outgoing      bool                   `protobuf:"varint,6,opt,name=outgoing,proto3" json:"outgoing,omitempty"` // true = I sent this, false = sent to me
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequestEntry) Reset() {
	*x = FriendRequestEntry{}
	mi := &file_veil_v1_friends_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequestEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequestEntry) ProtoMessage() {}

func (x *FriendRequestEntry) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_friends_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequestEntry.ProtoReflect.Descriptor instead.
func (*FriendRequestEntry) Descriptor() ([]byte, []int) {
	return file_veil_v1_friends_proto_rawDescGZIP(), []int{9}
}

func (x *FriendRequestEntry) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FriendRequestEntry) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *FriendRequestEntry) GetFromUsername() string {
	if x != nil {
		return x.FromUsername
	}
	return ""
}

func (x *FriendRequestEntry) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *FriendRequestEntry) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *FriendRequestEntry) GetOutgoing() bool {
	if x != nil {
		return x.Outgoing
	}
	return false
}

var File_veil_v1_friends_proto protoreflect.FileDescriptor

const file_veil_v1_friends_proto_rawDesc = "" +
	"\n" +
	"\x15veil/v1/friends.proto\x12\aveil.v1\x1a\x16veil/v1/presence.proto\"`\n" +
	"\rFriendRequest\x12$\n" +
	"\x0etarget_user_id\x18\x01 \x01(\tR\ftargetUserId\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\"\xc3\x01\n" +
	"\x12FriendRequestEvent\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12 \n" +
	"\ffrom_user_id\x18\x02 \x01(\tR\n" +
	"fromUserId\x12#\n" +
	"\rfrom_username\x18\x03 \x01(\tR\ffromUsername\x12\x1d\n" +
	"\amessage\x18\x04 \x01(\tH\x00R\amessage\x88\x01\x01\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x04R\ttimestampB\n" +
	"\n" +
	"\b_message\"F\n" +
	"\rFriendRespond\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06accept\x18\x02 \x01(\bR\x06accept\"J\n" +
	"\x13FriendAcceptedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"'\n" +
	"\fFriendRemove\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"-\n" +
	"\x12FriendRemovedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x13\n" +
	"\x11FriendListRequest\"\x8c\x01\n" +
	"\x12FriendListResponse\x12.\n" +
	"\afriends\x18\x01 \x03(\v2\x14.veil.v1.FriendEntryR\afriends\x12F\n" +
	"\x10pending_requests\x18\x02 \x03(\v2\x1b.veil.v1.FriendRequestEntryR\x0fpendingRequests\"\xa3\x01\n" +
	"\vFriendEntry\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12/\n" +
	"\x06status\x18\x03 \x01(\x0e2\x17.veil.v1.PresenceStatusR\x06status\x12 \n" +
	"\tlast_seen\x18\x04 \x01(\x04H\x00R\blastSeen\x88\x01\x01B\f\n" +
	"\n" +
	"_last_seen\"\xdf\x01\n" +
	"\x12FriendRequestEntry\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12 \n" +
	"\ffrom_user_id\x18\x02 \x01(\tR\n" +
	"fromUserId\x12#\n" +
	"\rfrom_username\x18\x03 \x01(\tR\ffromUsername\x12\x1d\n" +
	"\amessage\x18\x04 \x01(\tH\x00R\amessage\x88\x01\x01\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x04R\ttimestamp\x12\x1a\n" +
	"\boutgoing\x18\x06 \x01(\bR\boutgoingB\n" +
	"\n" +
	"\b_messageB.Z,github.com/AegisSec/veil-server/pkg/proto/v1b\x06proto3"

var (
	file_veil_v1_friends_proto_rawDescOnce sync.Once
	file_veil_v1_friends_proto_rawDescData []byte
)

func file_veil_v1_friends_proto_rawDescGZIP() []byte {
	file_veil_v1_friends_proto_rawDescOnce.Do(func() {
		file_veil_v1_friends_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_veil_v1_friends_proto_rawDesc), len(file_veil_v1_friends_proto_rawDesc)))
	})
	return file_veil_v1_friends_proto_rawDescData
}

var file_veil_v1_friends_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_veil_v1_friends_proto_goTypes = []any{
	(*FriendRequest)(nil),       // 0: veil.v1.FriendRequest
	(*FriendRequestEvent)(nil),  // 1: veil.v1.FriendRequestEvent
	(*FriendRespond)(nil),       // 2: veil.v1.FriendRespond
	(*FriendAcceptedEvent)(nil), // 3: veil.v1.FriendAcceptedEvent
	(*FriendRemove)(nil),        // 4: veil.v1.FriendRemove
	(*FriendRemovedEvent)(nil),  // 5: veil.v1.FriendRemovedEvent
	(*FriendListRequest)(nil),   // 6: veil.v1.FriendListRequest
	(*FriendListResponse)(nil),  // 7: veil.v1.FriendListResponse
	(*FriendEntry)(nil),         // 8: veil.v1.FriendEntry
	(*FriendRequestEntry)(nil),  // 9: veil.v1.FriendRequestEntry
	(PresenceStatus)(0),         // 10: veil.v1.PresenceStatus
}
var file_veil_v1_friends_proto_depIdxs = []int32{
	8,  // 0: veil.v1.FriendListResponse.friends:type_name -> veil.v1.FriendEntry
	9,  // 1: veil.v1.FriendListResponse.pending_requests:type_name -> veil.v1.FriendRequestEntry
	10, // 2: veil.v1.FriendEntry.status:type_name -> veil.v1.PresenceStatus
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_veil_v1_friends_proto_init() }
func file_veil_v1_friends_proto_init() {
	if File_veil_v1_friends_proto != nil {
		return
	}
	file_veil_v1_presence_proto_init()
	file_veil_v1_friends_proto_msgTypes[0].OneofWrappers = []any{}
	file_veil_v1_friends_proto_msgTypes[1].OneofWrappers = []any{}
	file_veil_v1_friends_proto_msgTypes[8].OneofWrappers = []any{}
	file_veil_v1_friends_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_veil_v1_friends_proto_rawDesc), len(file_veil_v1_friends_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_veil_v1_friends_proto_goTypes,
		DependencyIndexes: file_veil_v1_friends_proto_depIdxs,
		MessageInfos:      file_veil_v1_friends_proto_msgTypes,
	}.Build()
	File_veil_v1_friends_proto = out.File
	file_veil_v1_friends_proto_goTypes = nil
	file_veil_v1_friends_proto_depIdxs = nil
}
