// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: veil/v1/media.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SizeBytes     uint64                 `protobuf:"varint,1,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`       // MIME
	EncryptedName []byte                 `protobuf:"bytes,3,opt,name=encrypted_name,json=encryptedName,proto3" json:"encrypted_name,omitempty"` // Имя файла зашифровано
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaUploadRequest) Reset() {
	*x = MediaUploadRequest{}
	mi := &file_veil_v1_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaUploadRequest) ProtoMessage() {}

func (x *MediaUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaUploadRequest.ProtoReflect.Descriptor instead.
func (*MediaUploadRequest) Descriptor() ([]byte, []int) {
	return file_veil_v1_media_proto_rawDescGZIP(), []int{0}
}

func (x *MediaUploadRequest) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *MediaUploadRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *MediaUploadRequest) GetEncryptedName() []byte {
	if x != nil {
		return x.EncryptedName
	}
	return nil
}

type MediaUploadUrl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`        // ID для ссылки в сообщениях
	UploadUrl     string                 `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`  // Pre-signed S3 URL
	ExpiresAt     uint64                 `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // URL expiration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaUploadUrl) Reset() {
	*x = MediaUploadUrl{}
	mi := &file_veil_v1_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaUploadUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaUploadUrl) ProtoMessage() {}

func (x *MediaUploadUrl) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaUploadUrl.ProtoReflect.Descriptor instead.
func (*MediaUploadUrl) Descriptor() ([]byte, []int) {
	return file_veil_v1_media_proto_rawDescGZIP(), []int{1}
}

func (x *MediaUploadUrl) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *MediaUploadUrl) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *MediaUploadUrl) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

var File_veil_v1_media_proto protoreflect.FileDescriptor

const file_veil_v1_media_proto_rawDesc = "" +
	"\n" +
	"\x13veil/v1/media.proto\x12\aveil.v1\"}\n" +
	"\x12MediaUploadRequest\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x01 \x01(\x04R\tsizeBytes\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12%\n" +
	"\x0eencrypted_name\x18\x03 \x01(\fR\rencryptedName\"i\n" +
	"\x0eMediaUploadUrl\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\tR\tuploadUrl\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x04R\texpiresAtB.Z,github.com/AegisSec/veil-server/pkg/proto/v1b\x06proto3"

var (
	file_veil_v1_media_proto_rawDescOnce sync.Once
	file_veil_v1_media_proto_rawDescData []byte
)

func file_veil_v1_media_proto_rawDescGZIP() []byte {
	file_veil_v1_media_proto_rawDescOnce.Do(func() {
		file_veil_v1_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_veil_v1_media_proto_rawDesc), len(file_veil_v1_media_proto_rawDesc)))
	})
	return file_veil_v1_media_proto_rawDescData
}

var file_veil_v1_media_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_veil_v1_media_proto_goTypes = []any{
	(*MediaUploadRequest)(nil), // 0: veil.v1.MediaUploadRequest
	(*MediaUploadUrl)(nil),     // 1: veil.v1.MediaUploadUrl
}
var file_veil_v1_media_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_veil_v1_media_proto_init() }
func file_veil_v1_media_proto_init() {
	if File_veil_v1_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_veil_v1_media_proto_rawDesc), len(file_veil_v1_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_veil_v1_media_proto_goTypes,
		DependencyIndexes: file_veil_v1_media_proto_depIdxs,
		MessageInfos:      file_veil_v1_media_proto_msgTypes,
	}.Build()
	File_veil_v1_media_proto = out.File
	file_veil_v1_media_proto_goTypes = nil
	file_veil_v1_media_proto_depIdxs = nil
}
