// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: veil/v1/presence.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PresenceStatus int32

const (
	PresenceStatus_PRESENCE_UNKNOWN PresenceStatus = 0
	PresenceStatus_PRESENCE_ONLINE  PresenceStatus = 1
	PresenceStatus_PRESENCE_OFFLINE PresenceStatus = 2
	PresenceStatus_PRESENCE_AWAY    PresenceStatus = 3
	PresenceStatus_PRESENCE_DND     PresenceStatus = 4
)

// Enum value maps for PresenceStatus.
var (
	PresenceStatus_name = map[int32]string{
		0: "PRESENCE_UNKNOWN",
		1: "PRESENCE_ONLINE",
		2: "PRESENCE_OFFLINE",
		3: "PRESENCE_AWAY",
		4: "PRESENCE_DND",
	}
	PresenceStatus_value = map[string]int32{
		"PRESENCE_UNKNOWN": 0,
		"PRESENCE_ONLINE":  1,
		"PRESENCE_OFFLINE": 2,
		"PRESENCE_AWAY":    3,
		"PRESENCE_DND":     4,
	}
)

func (x PresenceStatus) Enum() *PresenceStatus {
	p := new(PresenceStatus)
	*p = x
	return p
}

func (x PresenceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PresenceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_veil_v1_presence_proto_enumTypes[0].Descriptor()
}

func (PresenceStatus) Type() protoreflect.EnumType {
	return &file_veil_v1_presence_proto_enumTypes[0]
}

func (x PresenceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PresenceStatus.Descriptor instead.
func (PresenceStatus) EnumDescriptor() ([]byte, []int) {
	return file_veil_v1_presence_proto_rawDescGZIP(), []int{0}
}

type PresenceUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityKey   []byte                 `protobuf:"bytes,1,opt,name=identity_key,json=identityKey,proto3" json:"identity_key,omitempty"`
	Status        PresenceStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=veil.v1.PresenceStatus" json:"status,omitempty"`
	StatusText    *string                `protobuf:"bytes,3,opt,name=status_text,json=statusText,proto3,oneof" json:"status_text,omitempty"`
	LastSeen      *uint64                `protobuf:"varint,4,opt,name=last_seen,json=lastSeen,proto3,oneof" json:"last_seen,omitempty"` // timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceUpdate) Reset() {
	*x = PresenceUpdate{}
	mi := &file_veil_v1_presence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceUpdate) ProtoMessage() {}

func (x *PresenceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_presence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceUpdate.ProtoReflect.Descriptor instead.
func (*PresenceUpdate) Descriptor() ([]byte, []int) {
	return file_veil_v1_presence_proto_rawDescGZIP(), []int{0}
}

func (x *PresenceUpdate) GetIdentityKey() []byte {
	if x != nil {
		return x.IdentityKey
	}
	return nil
}

func (x *PresenceUpdate) GetStatus() PresenceStatus {
	if x != nil {
		return x.Status
	}
	return PresenceStatus_PRESENCE_UNKNOWN
}

func (x *PresenceUpdate) GetStatusText() string {
	if x != nil && x.StatusText != nil {
		return *x.StatusText
	}
	return ""
}

func (x *PresenceUpdate) GetLastSeen() uint64 {
	if x != nil && x.LastSeen != nil {
		return *x.LastSeen
	}
	return 0
}

type TypingEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	IdentityKey    []byte                 `protobuf:"bytes,2,opt,name=identity_key,json=identityKey,proto3" json:"identity_key,omitempty"`
	Started        bool                   `protobuf:"varint,3,opt,name=started,proto3" json:"started,omitempty"` // true = started typing, false = stopped
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TypingEvent) Reset() {
	*x = TypingEvent{}
	mi := &file_veil_v1_presence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypingEvent) ProtoMessage() {}

func (x *TypingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_presence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypingEvent.ProtoReflect.Descriptor instead.
func (*TypingEvent) Descriptor() ([]byte, []int) {
	return file_veil_v1_presence_proto_rawDescGZIP(), []int{1}
}

func (x *TypingEvent) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *TypingEvent) GetIdentityKey() []byte {
	if x != nil {
		return x.IdentityKey
	}
	return nil
}

func (x *TypingEvent) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

var File_veil_v1_presence_proto protoreflect.FileDescriptor

const file_veil_v1_presence_proto_rawDesc = "" +
	"\n" +
	"\x16veil/v1/presence.proto\x12\aveil.v1\"\xca\x01\n" +
	"\x0ePresenceUpdate\x12!\n" +
	"\fidentity_key\x18\x01 \x01(\fR\videntityKey\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.veil.v1.PresenceStatusR\x06status\x12$\n" +
	"\vstatus_text\x18\x03 \x01(\tH\x00R\n" +
	"statusText\x88\x01\x01\x12 \n" +
	"\tlast_seen\x18\x04 \x01(\x04H\x01R\blastSeen\x88\x01\x01B\x0e\n" +
	"\f_status_textB\f\n" +
	"\n" +
	"_last_seen\"s\n" +
	"\vTypingEvent\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12!\n" +
	"\fidentity_key\x18\x02 \x01(\fR\videntityKey\x12\x18\n" +
	"\astarted\x18\x03 \x01(\bR\astarted*v\n" +
	"\x0ePresenceStatus\x12\x14\n" +
	"\x10PRESENCE_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fPRESENCE_ONLINE\x10\x01\x12\x14\n" +
	"\x10PRESENCE_OFFLINE\x10\x02\x12\x11\n" +
	"\rPRESENCE_AWAY\x10\x03\x12\x10\n" +
	"\fPRESENCE_DND\x10\x04B.Z,github.com/AegisSec/veil-server/pkg/proto/v1b\x06proto3"

var (
	file_veil_v1_presence_proto_rawDescOnce sync.Once
	file_veil_v1_presence_proto_rawDescData []byte
)

func file_veil_v1_presence_proto_rawDescGZIP() []byte {
	file_veil_v1_presence_proto_rawDescOnce.Do(func() {
		file_veil_v1_presence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_veil_v1_presence_proto_rawDesc), len(file_veil_v1_presence_proto_rawDesc)))
	})
	return file_veil_v1_presence_proto_rawDescData
}

var file_veil_v1_presence_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_veil_v1_presence_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_veil_v1_presence_proto_goTypes = []any{
	(PresenceStatus)(0),    // 0: veil.v1.PresenceStatus
	(*PresenceUpdate)(nil), // 1: veil.v1.PresenceUpdate
	(*TypingEvent)(nil),    // 2: veil.v1.TypingEvent
}
var file_veil_v1_presence_proto_depIdxs = []int32{
	0, // 0: veil.v1.PresenceUpdate.status:type_name -> veil.v1.PresenceStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_veil_v1_presence_proto_init() }
func file_veil_v1_presence_proto_init() {
	if File_veil_v1_presence_proto != nil {
		return
	}
	file_veil_v1_presence_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_veil_v1_presence_proto_rawDesc), len(file_veil_v1_presence_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_veil_v1_presence_proto_goTypes,
		DependencyIndexes: file_veil_v1_presence_proto_depIdxs,
		EnumInfos:         file_veil_v1_presence_proto_enumTypes,
		MessageInfos:      file_veil_v1_presence_proto_msgTypes,
	}.Build()
	File_veil_v1_presence_proto = out.File
	file_veil_v1_presence_proto_goTypes = nil
	file_veil_v1_presence_proto_depIdxs = nil
}
