// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: veil/v1/profile.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Presentation-only invalidation hint. Profile contents remain on the signed
// REST surface and must be fetched again for the exact authenticated origin.
type ProfileUpdated struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProfileVersion uint64                 `protobuf:"varint,2,opt,name=profile_version,json=profileVersion,proto3" json:"profile_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProfileUpdated) Reset() {
	*x = ProfileUpdated{}
	mi := &file_veil_v1_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileUpdated) ProtoMessage() {}

func (x *ProfileUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileUpdated.ProtoReflect.Descriptor instead.
func (*ProfileUpdated) Descriptor() ([]byte, []int) {
	return file_veil_v1_profile_proto_rawDescGZIP(), []int{0}
}

func (x *ProfileUpdated) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProfileUpdated) GetProfileVersion() uint64 {
	if x != nil {
		return x.ProfileVersion
	}
	return 0
}

var File_veil_v1_profile_proto protoreflect.FileDescriptor

const file_veil_v1_profile_proto_rawDesc = "" +
	"\n" +
	"\x15veil/v1/profile.proto\x12\aveil.v1\"R\n" +
	"\x0eProfileUpdated\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fprofile_version\x18\x02 \x01(\x04R\x0eprofileVersionB.Z,github.com/AegisSec/veil-server/pkg/proto/v1b\x06proto3"

var (
	file_veil_v1_profile_proto_rawDescOnce sync.Once
	file_veil_v1_profile_proto_rawDescData []byte
)

func file_veil_v1_profile_proto_rawDescGZIP() []byte {
	file_veil_v1_profile_proto_rawDescOnce.Do(func() {
		file_veil_v1_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_veil_v1_profile_proto_rawDesc), len(file_veil_v1_profile_proto_rawDesc)))
	})
	return file_veil_v1_profile_proto_rawDescData
}

var file_veil_v1_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_veil_v1_profile_proto_goTypes = []any{
	(*ProfileUpdated)(nil), // 0: veil.v1.ProfileUpdated
}
var file_veil_v1_profile_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_veil_v1_profile_proto_init() }
func file_veil_v1_profile_proto_init() {
	if File_veil_v1_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_veil_v1_profile_proto_rawDesc), len(file_veil_v1_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_veil_v1_profile_proto_goTypes,
		DependencyIndexes: file_veil_v1_profile_proto_depIdxs,
		MessageInfos:      file_veil_v1_profile_proto_msgTypes,
	}.Build()
	File_veil_v1_profile_proto = out.File
	file_veil_v1_profile_proto_goTypes = nil
	file_veil_v1_profile_proto_depIdxs = nil
}
