// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: veil/v1/server.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChannelType int32

const (
	ChannelType_CHANNEL_TEXT     ChannelType = 0
	ChannelType_CHANNEL_VOICE    ChannelType = 1
	ChannelType_CHANNEL_CATEGORY ChannelType = 2
)

// Enum value maps for ChannelType.
var (
	ChannelType_name = map[int32]string{
		0: "CHANNEL_TEXT",
		1: "CHANNEL_VOICE",
		2: "CHANNEL_CATEGORY",
	}
	ChannelType_value = map[string]int32{
		"CHANNEL_TEXT":     0,
		"CHANNEL_VOICE":    1,
		"CHANNEL_CATEGORY": 2,
	}
)

func (x ChannelType) Enum() *ChannelType {
	p := new(ChannelType)
	*p = x
	return p
}

func (x ChannelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelType) Descriptor() protoreflect.EnumDescriptor {
	return file_veil_v1_server_proto_enumTypes[0].Descriptor()
}

func (ChannelType) Type() protoreflect.EnumType {
	return &file_veil_v1_server_proto_enumTypes[0]
}

func (x ChannelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChannelType.Descriptor instead.
func (ChannelType) EnumDescriptor() ([]byte, []int) {
	return file_veil_v1_server_proto_rawDescGZIP(), []int{0}
}

type ServerEvent_EventType int32

const (
	ServerEvent_CREATED       ServerEvent_EventType = 0
	ServerEvent_UPDATED       ServerEvent_EventType = 1
	ServerEvent_DELETED       ServerEvent_EventType = 2
	ServerEvent_MEMBER_JOINED ServerEvent_EventType = 3
	ServerEvent_MEMBER_LEFT   ServerEvent_EventType = 4
	ServerEvent_MEMBER_KICKED ServerEvent_EventType = 5
	ServerEvent_MEMBER_BANNED ServerEvent_EventType = 6
	ServerEvent_ROLE_CREATED  ServerEvent_EventType = 7
	ServerEvent_ROLE_UPDATED  ServerEvent_EventType = 8
	ServerEvent_ROLE_DELETED  ServerEvent_EventType = 9
)

// Enum value maps for ServerEvent_EventType.
var (
	ServerEvent_EventType_name = map[int32]string{
		0: "CREATED",
		1: "UPDATED",
		2: "DELETED",
		3: "MEMBER_JOINED",
		4: "MEMBER_LEFT",
		5: "MEMBER_KICKED",
		6: "MEMBER_BANNED",
		7: "ROLE_CREATED",
		8: "ROLE_UPDATED",
		9: "ROLE_DELETED",
	}
	ServerEvent_EventType_value = map[string]int32{
		"CREATED":       0,
		"UPDATED":       1,
		"DELETED":       2,
		"MEMBER_JOINED": 3,
		"MEMBER_LEFT":   4,
		"MEMBER_KICKED": 5,
		"MEMBER_BANNED": 6,
		"ROLE_CREATED":  7,
		"ROLE_UPDATED":  8,
		"ROLE_DELETED":  9,
	}
)

func (x ServerEvent_EventType) Enum() *ServerEvent_EventType {
	p := new(ServerEvent_EventType)
	*p = x
	return p
}

func (x ServerEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_veil_v1_server_proto_enumTypes[1].Descriptor()
}

func (ServerEvent_EventType) Type() protoreflect.EnumType {
	return &file_veil_v1_server_proto_enumTypes[1]
}

func (x ServerEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerEvent_EventType.Descriptor instead.
func (ServerEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_veil_v1_server_proto_rawDescGZIP(), []int{0, 0}
}

type ChannelEvent_EventType int32

const (
	ChannelEvent_CREATED   ChannelEvent_EventType = 0
	ChannelEvent_UPDATED   ChannelEvent_EventType = 1
	ChannelEvent_DELETED   ChannelEvent_EventType = 2
	ChannelEvent_REORDERED ChannelEvent_EventType = 3
)

// Enum value maps for ChannelEvent_EventType.
var (
	ChannelEvent_EventType_name = map[int32]string{
		0: "CREATED",
		1: "UPDATED",
		2: "DELETED",
		3: "REORDERED",
	}
	ChannelEvent_EventType_value = map[string]int32{
		"CREATED":   0,
		"UPDATED":   1,
		"DELETED":   2,
		"REORDERED": 3,
	}
)

func (x ChannelEvent_EventType) Enum() *ChannelEvent_EventType {
	p := new(ChannelEvent_EventType)
	*p = x
	return p
}

func (x ChannelEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_veil_v1_server_proto_enumTypes[2].Descriptor()
}

func (ChannelEvent_EventType) Type() protoreflect.EnumType {
	return &file_veil_v1_server_proto_enumTypes[2]
}

func (x ChannelEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChannelEvent_EventType.Descriptor instead.
func (ChannelEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_veil_v1_server_proto_rawDescGZIP(), []int{4, 0}
}

type ServerEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EventType ServerEvent_EventType  `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=veil.v1.ServerEvent_EventType" json:"event_type,omitempty"`
	ServerId  string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// Контекстные поля (заполняются в зависимости от event_type)
	ServerInfo    *ServerInfo `protobuf:"bytes,3,opt,name=server_info,json=serverInfo,proto3,oneof" json:"server_info,omitempty"`
	MemberInfo    *MemberInfo `protobuf:"bytes,4,opt,name=member_info,json=memberInfo,proto3,oneof" json:"member_info,omitempty"`
	RoleInfo      *RoleInfo   `protobuf:"bytes,5,opt,name=role_info,json=roleInfo,proto3,oneof" json:"role_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_veil_v1_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_veil_v1_server_proto_rawDescGZIP(), []int{0}
}

func (x *ServerEvent) GetEventType() ServerEvent_EventType {
	if x != nil {
		return x.EventType
	}
	return ServerEvent_CREATED
}

func (x *ServerEvent) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServerEvent) GetServerInfo() *ServerInfo {
	if x != nil {
		return x.ServerInfo
	}
	return nil
}

func (x *ServerEvent) GetMemberInfo() *MemberInfo {
	if x != nil {
		return x.MemberInfo
	}
	return nil
}

func (x *ServerEvent) GetRoleInfo() *RoleInfo {
	if x != nil {
		return x.RoleInfo
	}
	return nil
}

type ServerInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IconUrl          *string                `protobuf:"bytes,3,opt,name=icon_url,json=iconUrl,proto3,oneof" json:"icon_url,omitempty"`
	OwnerIdentityKey []byte                 `protobuf:"bytes,4,opt,name=owner_identity_key,json=ownerIdentityKey,proto3" json:"owner_identity_key,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_veil_v1_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_veil_v1_server_proto_rawDescGZIP(), []int{1}
}

func (x *ServerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerInfo) GetIconUrl() string {
	if x != nil && x.IconUrl != nil {
		return *x.IconUrl
	}
	return ""
}

func (x *ServerInfo) GetOwnerIdentityKey() []byte {
	if x != nil {
		return x.OwnerIdentityKey
	}
	return nil
}

type MemberInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityKey   []byte                 `protobuf:"bytes,1,opt,name=identity_key,json=identityKey,proto3" json:"identity_key,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	RoleIds       []string               `protobuf:"bytes,3,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	Reason        *string                `protobuf:"bytes,4,opt,name=reason,proto3,oneof" json:"reason,omitempty"` // Для kick/ban
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberInfo) Reset() {
	*x = MemberInfo{}
	mi := &file_veil_v1_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberInfo) ProtoMessage() {}

func (x *MemberInfo) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberInfo.ProtoReflect.Descriptor instead.
func (*MemberInfo) Descriptor() ([]byte, []int) {
	return file_veil_v1_server_proto_rawDescGZIP(), []int{2}
}

func (x *MemberInfo) GetIdentityKey() []byte {
	if x != nil {
		return x.IdentityKey
	}
	return nil
}

func (x *MemberInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *MemberInfo) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *MemberInfo) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type RoleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Permissions   uint64                 `protobuf:"varint,3,opt,name=permissions,proto3" json:"permissions,omitempty"` // Bitmask
	Position      uint32                 `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	Color         *uint32                `protobuf:"varint,5,opt,name=color,proto3,oneof" json:"color,omitempty"` // RGB
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleInfo) Reset() {
	*x = RoleInfo{}
	mi := &file_veil_v1_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfo) ProtoMessage() {}

func (x *RoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfo.ProtoReflect.Descriptor instead.
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return file_veil_v1_server_proto_rawDescGZIP(), []int{3}
}

func (x *RoleInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleInfo) GetPermissions() uint64 {
	if x != nil {
		return x.Permissions
	}
	return 0
}

func (x *RoleInfo) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *RoleInfo) GetColor() uint32 {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return 0
}

type ChannelEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     ChannelEvent_EventType `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=veil.v1.ChannelEvent_EventType" json:"event_type,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ChannelInfo   *ChannelInfo           `protobuf:"bytes,3,opt,name=channel_info,json=channelInfo,proto3" json:"channel_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelEvent) Reset() {
	*x = ChannelEvent{}
	mi := &file_veil_v1_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelEvent) ProtoMessage() {}

func (x *ChannelEvent) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelEvent.ProtoReflect.Descriptor instead.
func (*ChannelEvent) Descriptor() ([]byte, []int) {
	return file_veil_v1_server_proto_rawDescGZIP(), []int{4}
}

func (x *ChannelEvent) GetEventType() ChannelEvent_EventType {
	if x != nil {
		return x.EventType
	}
	return ChannelEvent_CREATED
}

func (x *ChannelEvent) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ChannelEvent) GetChannelInfo() *ChannelInfo {
	if x != nil {
		return x.ChannelInfo
	}
	return nil
}

type ChannelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ChannelType   ChannelType            `protobuf:"varint,4,opt,name=channel_type,json=channelType,proto3,enum=veil.v1.ChannelType" json:"channel_type,omitempty"`
	CategoryId    *string                `protobuf:"bytes,5,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	Position      uint32                 `protobuf:"varint,6,opt,name=position,proto3" json:"position,omitempty"`
	Topic         *string                `protobuf:"bytes,7,opt,name=topic,proto3,oneof" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelInfo) Reset() {
	*x = ChannelInfo{}
	mi := &file_veil_v1_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelInfo) ProtoMessage() {}

func (x *ChannelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelInfo.ProtoReflect.Descriptor instead.
func (*ChannelInfo) Descriptor() ([]byte, []int) {
	return file_veil_v1_server_proto_rawDescGZIP(), []int{5}
}

func (x *ChannelInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChannelInfo) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ChannelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChannelInfo) GetChannelType() ChannelType {
	if x != nil {
		return x.ChannelType
	}
	return ChannelType_CHANNEL_TEXT
}

func (x *ChannelInfo) GetCategoryId() string {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return ""
}

func (x *ChannelInfo) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *ChannelInfo) GetTopic() string {
	if x != nil && x.Topic != nil {
		return *x.Topic
	}
	return ""
}

type SyncRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LastSyncTimestamp uint64                 `protobuf:"varint,1,opt,name=last_sync_timestamp,json=lastSyncTimestamp,proto3" json:"last_sync_timestamp,omitempty"` // Всё после этого момента
	ConversationId    *string                `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3,oneof" json:"conversation_id,omitempty"`       // Или конкретный conversation
	Limit             uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_veil_v1_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_veil_v1_server_proto_rawDescGZIP(), []int{6}
}

func (x *SyncRequest) GetLastSyncTimestamp() uint64 {
	if x != nil {
		return x.LastSyncTimestamp
	}
	return 0
}

func (x *SyncRequest) GetConversationId() string {
	if x != nil && x.ConversationId != nil {
		return *x.ConversationId
	}
	return ""
}

func (x *SyncRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SyncBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*MessageEvent        `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Presences     []*PresenceUpdate      `protobuf:"bytes,2,rep,name=presences,proto3" json:"presences,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	SyncTimestamp uint64                 `protobuf:"varint,4,opt,name=sync_timestamp,json=syncTimestamp,proto3" json:"sync_timestamp,omitempty"` // Новая "точка синхронизации"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncBatch) Reset() {
	*x = SyncBatch{}
	mi := &file_veil_v1_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncBatch) ProtoMessage() {}

func (x *SyncBatch) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncBatch.ProtoReflect.Descriptor instead.
func (*SyncBatch) Descriptor() ([]byte, []int) {
	return file_veil_v1_server_proto_rawDescGZIP(), []int{7}
}

func (x *SyncBatch) GetMessages() []*MessageEvent {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *SyncBatch) GetPresences() []*PresenceUpdate {
	if x != nil {
		return x.Presences
	}
	return nil
}

func (x *SyncBatch) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *SyncBatch) GetSyncTimestamp() uint64 {
	if x != nil {
		return x.SyncTimestamp
	}
	return 0
}

var File_veil_v1_server_proto protoreflect.FileDescriptor

const file_veil_v1_server_proto_rawDesc = "" +
	"\n" +
	"\x14veil/v1/server.proto\x12\aveil.v1\x1a\x12veil/v1/chat.proto\x1a\x16veil/v1/presence.proto\"\xf7\x03\n" +
	"\vServerEvent\x12=\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2\x1e.veil.v1.ServerEvent.EventTypeR\teventType\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x129\n" +
	"\vserver_info\x18\x03 \x01(\v2\x13.veil.v1.ServerInfoH\x00R\n" +
	"serverInfo\x88\x01\x01\x129\n" +
	"\vmember_info\x18\x04 \x01(\v2\x13.veil.v1.MemberInfoH\x01R\n" +
	"memberInfo\x88\x01\x01\x123\n" +
	"\trole_info\x18\x05 \x01(\v2\x11.veil.v1.RoleInfoH\x02R\broleInfo\x88\x01\x01\"\xb2\x01\n" +
	"\tEventType\x12\v\n" +
	"\aCREATED\x10\x00\x12\v\n" +
	"\aUPDATED\x10\x01\x12\v\n" +
	"\aDELETED\x10\x02\x12\x11\n" +
	"\rMEMBER_JOINED\x10\x03\x12\x0f\n" +
	"\vMEMBER_LEFT\x10\x04\x12\x11\n" +
	"\rMEMBER_KICKED\x10\x05\x12\x11\n" +
	"\rMEMBER_BANNED\x10\x06\x12\x10\n" +
	"\fROLE_CREATED\x10\a\x12\x10\n" +
	"\fROLE_UPDATED\x10\b\x12\x10\n" +
	"\fROLE_DELETED\x10\tB\x0e\n" +
	"\f_server_infoB\x0e\n" +
	"\f_member_infoB\f\n" +
	"\n" +
	"_role_info\"\x8b\x01\n" +
	"\n" +
	"ServerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\bicon_url\x18\x03 \x01(\tH\x00R\aiconUrl\x88\x01\x01\x12,\n" +
	"\x12owner_identity_key\x18\x04 \x01(\fR\x10ownerIdentityKeyB\v\n" +
	"\t_icon_url\"\x8e\x01\n" +
	"\n" +
	"MemberInfo\x12!\n" +
	"\fidentity_key\x18\x01 \x01(\fR\videntityKey\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x19\n" +
	"\brole_ids\x18\x03 \x03(\tR\aroleIds\x12\x1b\n" +
	"\x06reason\x18\x04 \x01(\tH\x00R\x06reason\x88\x01\x01B\t\n" +
	"\a_reason\"\x91\x01\n" +
	"\bRoleInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vpermissions\x18\x03 \x01(\x04R\vpermissions\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\rR\bposition\x12\x19\n" +
	"\x05color\x18\x05 \x01(\rH\x00R\x05color\x88\x01\x01B\b\n" +
	"\x06_color\"\xe7\x01\n" +
	"\fChannelEvent\x12>\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2\x1f.veil.v1.ChannelEvent.EventTypeR\teventType\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x127\n" +
	"\fchannel_info\x18\x03 \x01(\v2\x14.veil.v1.ChannelInfoR\vchannelInfo\"A\n" +
	"\tEventType\x12\v\n" +
	"\aCREATED\x10\x00\x12\v\n" +
	"\aUPDATED\x10\x01\x12\v\n" +
	"\aDELETED\x10\x02\x12\r\n" +
	"\tREORDERED\x10\x03\"\xfe\x01\n" +
	"\vChannelInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x127\n" +
	"\fchannel_type\x18\x04 \x01(\x0e2\x14.veil.v1.ChannelTypeR\vchannelType\x12$\n" +
	"\vcategory_id\x18\x05 \x01(\tH\x00R\n" +
	"categoryId\x88\x01\x01\x12\x1a\n" +
	"\bposition\x18\x06 \x01(\rR\bposition\x12\x19\n" +
	"\x05topic\x18\a \x01(\tH\x01R\x05topic\x88\x01\x01B\x0e\n" +
	"\f_category_idB\b\n" +
	"\x06_topic\"\x95\x01\n" +
	"\vSyncRequest\x12.\n" +
	"\x13last_sync_timestamp\x18\x01 \x01(\x04R\x11lastSyncTimestamp\x12,\n" +
	"\x0fconversation_id\x18\x02 \x01(\tH\x00R\x0econversationId\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limitB\x12\n" +
	"\x10_conversation_id\"\xb7\x01\n" +
	"\tSyncBatch\x121\n" +
	"\bmessages\x18\x01 \x03(\v2\x15.veil.v1.MessageEventR\bmessages\x125\n" +
	"\tpresences\x18\x02 \x03(\v2\x17.veil.v1.PresenceUpdateR\tpresences\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\x12%\n" +
	"\x0esync_timestamp\x18\x04 \x01(\x04R\rsyncTimestamp*H\n" +
	"\vChannelType\x12\x10\n" +
	"\fCHANNEL_TEXT\x10\x00\x12\x11\n" +
	"\rCHANNEL_VOICE\x10\x01\x12\x14\n" +
	"\x10CHANNEL_CATEGORY\x10\x02B.Z,github.com/AegisSec/veil-server/pkg/proto/v1b\x06proto3"

var (
	file_veil_v1_server_proto_rawDescOnce sync.Once
	file_veil_v1_server_proto_rawDescData []byte
)

func file_veil_v1_server_proto_rawDescGZIP() []byte {
	file_veil_v1_server_proto_rawDescOnce.Do(func() {
		file_veil_v1_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_veil_v1_server_proto_rawDesc), len(file_veil_v1_server_proto_rawDesc)))
	})
	return file_veil_v1_server_proto_rawDescData
}

var file_veil_v1_server_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_veil_v1_server_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_veil_v1_server_proto_goTypes = []any{
	(ChannelType)(0),            // 0: veil.v1.ChannelType
	(ServerEvent_EventType)(0),  // 1: veil.v1.ServerEvent.EventType
	(ChannelEvent_EventType)(0), // 2: veil.v1.ChannelEvent.EventType
	(*ServerEvent)(nil),         // 3: veil.v1.ServerEvent
	(*ServerInfo)(nil),          // 4: veil.v1.ServerInfo
	(*MemberInfo)(nil),          // 5: veil.v1.MemberInfo
	(*RoleInfo)(nil),            // 6: veil.v1.RoleInfo
	(*ChannelEvent)(nil),        // 7: veil.v1.ChannelEvent
	(*ChannelInfo)(nil),         // 8: veil.v1.ChannelInfo
	(*SyncRequest)(nil),         // 9: veil.v1.SyncRequest
	(*SyncBatch)(nil),           // 10: veil.v1.SyncBatch
	(*MessageEvent)(nil),        // 11: veil.v1.MessageEvent
	(*PresenceUpdate)(nil),      // 12: veil.v1.PresenceUpdate
}
var file_veil_v1_server_proto_depIdxs = []int32{
	1,  // 0: veil.v1.ServerEvent.event_type:type_name -> veil.v1.ServerEvent.EventType
	4,  // 1: veil.v1.ServerEvent.server_info:type_name -> veil.v1.ServerInfo
	5,  // 2: veil.v1.ServerEvent.member_info:type_name -> veil.v1.MemberInfo
	6,  // 3: veil.v1.ServerEvent.role_info:type_name -> veil.v1.RoleInfo
	2,  // 4: veil.v1.ChannelEvent.event_type:type_name -> veil.v1.ChannelEvent.EventType
	8,  // 5: veil.v1.ChannelEvent.channel_info:type_name -> veil.v1.ChannelInfo
	0,  // 6: veil.v1.ChannelInfo.channel_type:type_name -> veil.v1.ChannelType
	11, // 7: veil.v1.SyncBatch.messages:type_name -> veil.v1.MessageEvent
	12, // 8: veil.v1.SyncBatch.presences:type_name -> veil.v1.PresenceUpdate
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_veil_v1_server_proto_init() }
func file_veil_v1_server_proto_init() {
	if File_veil_v1_server_proto != nil {
		return
	}
	file_veil_v1_chat_proto_init()
	file_veil_v1_presence_proto_init()
	file_veil_v1_server_proto_msgTypes[0].OneofWrappers = []any{}
	file_veil_v1_server_proto_msgTypes[1].OneofWrappers = []any{}
	file_veil_v1_server_proto_msgTypes[2].OneofWrappers = []any{}
	file_veil_v1_server_proto_msgTypes[3].OneofWrappers = []any{}
	file_veil_v1_server_proto_msgTypes[5].OneofWrappers = []any{}
	file_veil_v1_server_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_veil_v1_server_proto_rawDesc), len(file_veil_v1_server_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_veil_v1_server_proto_goTypes,
		DependencyIndexes: file_veil_v1_server_proto_depIdxs,
		EnumInfos:         file_veil_v1_server_proto_enumTypes,
		MessageInfos:      file_veil_v1_server_proto_msgTypes,
	}.Build()
	File_veil_v1_server_proto = out.File
	file_veil_v1_server_proto_goTypes = nil
	file_veil_v1_server_proto_depIdxs = nil
}
