// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: veil/v1/share.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Клиент → сервер: создать secure share
type ShareCreate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ciphertext    []byte                 `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`                            // Зашифрованный payload (клиент шифрует)
	HasPassword   bool                   `protobuf:"varint,2,opt,name=has_password,json=hasPassword,proto3" json:"has_password,omitempty"`      // Защищён паролем?
	MaxViews      uint32                 `protobuf:"varint,3,opt,name=max_views,json=maxViews,proto3" json:"max_views,omitempty"`               // Макс. кол-во просмотров (1-100)
	TtlSeconds    uint64                 `protobuf:"varint,4,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`         // Время жизни в секундах
	SizeBytes     uint64                 `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`            // Размер оригинальных данных (для UI)
	ContentType   *string                `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3,oneof" json:"content_type,omitempty"` // "text", "file", "multi"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareCreate) Reset() {
	*x = ShareCreate{}
	mi := &file_veil_v1_share_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareCreate) ProtoMessage() {}

func (x *ShareCreate) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_share_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareCreate.ProtoReflect.Descriptor instead.
func (*ShareCreate) Descriptor() ([]byte, []int) {
	return file_veil_v1_share_proto_rawDescGZIP(), []int{0}
}

func (x *ShareCreate) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *ShareCreate) GetHasPassword() bool {
	if x != nil {
		return x.HasPassword
	}
	return false
}

func (x *ShareCreate) GetMaxViews() uint32 {
	if x != nil {
		return x.MaxViews
	}
	return 0
}

func (x *ShareCreate) GetTtlSeconds() uint64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *ShareCreate) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ShareCreate) GetContentType() string {
	if x != nil && x.ContentType != nil {
		return *x.ContentType
	}
	return ""
}

// Сервер → клиент: share создан
type ShareCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShareId       string                 `protobuf:"bytes,1,opt,name=share_id,json=shareId,proto3" json:"share_id,omitempty"`        // Short random ID
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`                               // Full URL: https://domain/s/{id}
	ExpiresAt     uint64                 `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Timestamp expiration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareCreated) Reset() {
	*x = ShareCreated{}
	mi := &file_veil_v1_share_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareCreated) ProtoMessage() {}

func (x *ShareCreated) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_share_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareCreated.ProtoReflect.Descriptor instead.
func (*ShareCreated) Descriptor() ([]byte, []int) {
	return file_veil_v1_share_proto_rawDescGZIP(), []int{1}
}

func (x *ShareCreated) GetShareId() string {
	if x != nil {
		return x.ShareId
	}
	return ""
}

func (x *ShareCreated) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ShareCreated) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

var File_veil_v1_share_proto protoreflect.FileDescriptor

const file_veil_v1_share_proto_rawDesc = "" +
	"\n" +
	"\x13veil/v1/share.proto\x12\aveil.v1\"\xe6\x01\n" +
	"\vShareCreate\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x01 \x01(\fR\n" +
	"ciphertext\x12!\n" +
	"\fhas_password\x18\x02 \x01(\bR\vhasPassword\x12\x1b\n" +
	"\tmax_views\x18\x03 \x01(\rR\bmaxViews\x12\x1f\n" +
	"\vttl_seconds\x18\x04 \x01(\x04R\n" +
	"ttlSeconds\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x04R\tsizeBytes\x12&\n" +
	"\fcontent_type\x18\x06 \x01(\tH\x00R\vcontentType\x88\x01\x01B\x0f\n" +
	"\r_content_type\"Z\n" +
	"\fShareCreated\x12\x19\n" +
	"\bshare_id\x18\x01 \x01(\tR\ashareId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x04R\texpiresAtB.Z,github.com/AegisSec/veil-server/pkg/proto/v1b\x06proto3"

var (
	file_veil_v1_share_proto_rawDescOnce sync.Once
	file_veil_v1_share_proto_rawDescData []byte
)

func file_veil_v1_share_proto_rawDescGZIP() []byte {
	file_veil_v1_share_proto_rawDescOnce.Do(func() {
		file_veil_v1_share_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_veil_v1_share_proto_rawDesc), len(file_veil_v1_share_proto_rawDesc)))
	})
	return file_veil_v1_share_proto_rawDescData
}

var file_veil_v1_share_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_veil_v1_share_proto_goTypes = []any{
	(*ShareCreate)(nil),  // 0: veil.v1.ShareCreate
	(*ShareCreated)(nil), // 1: veil.v1.ShareCreated
}
var file_veil_v1_share_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_veil_v1_share_proto_init() }
func file_veil_v1_share_proto_init() {
	if File_veil_v1_share_proto != nil {
		return
	}
	file_veil_v1_share_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_veil_v1_share_proto_rawDesc), len(file_veil_v1_share_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_veil_v1_share_proto_goTypes,
		DependencyIndexes: file_veil_v1_share_proto_depIdxs,
		MessageInfos:      file_veil_v1_share_proto_msgTypes,
	}.Build()
	File_veil_v1_share_proto = out.File
	file_veil_v1_share_proto_goTypes = nil
	file_veil_v1_share_proto_depIdxs = nil
}
