// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: veil/v1/voice.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VoiceTokenRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // Channel, DM, or group
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VoiceTokenRequest) Reset() {
	*x = VoiceTokenRequest{}
	mi := &file_veil_v1_voice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceTokenRequest) ProtoMessage() {}

func (x *VoiceTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_voice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceTokenRequest.ProtoReflect.Descriptor instead.
func (*VoiceTokenRequest) Descriptor() ([]byte, []int) {
	return file_veil_v1_voice_proto_rawDescGZIP(), []int{0}
}

func (x *VoiceTokenRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type VoiceToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                          // LiveKit JWT token
	ServerUrl     string                 `protobuf:"bytes,2,opt,name=server_url,json=serverUrl,proto3" json:"server_url,omitempty"` // LiveKit server URL
	RoomName      string                 `protobuf:"bytes,3,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceToken) Reset() {
	*x = VoiceToken{}
	mi := &file_veil_v1_voice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceToken) ProtoMessage() {}

func (x *VoiceToken) ProtoReflect() protoreflect.Message {
	mi := &file_veil_v1_voice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceToken.ProtoReflect.Descriptor instead.
func (*VoiceToken) Descriptor() ([]byte, []int) {
	return file_veil_v1_voice_proto_rawDescGZIP(), []int{1}
}

func (x *VoiceToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *VoiceToken) GetServerUrl() string {
	if x != nil {
		return x.ServerUrl
	}
	return ""
}

func (x *VoiceToken) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

var File_veil_v1_voice_proto protoreflect.FileDescriptor

const file_veil_v1_voice_proto_rawDesc = "" +
	"\n" +
	"\x13veil/v1/voice.proto\x12\aveil.v1\"<\n" +
	"\x11VoiceTokenRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\"^\n" +
	"\n" +
	"VoiceToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"server_url\x18\x02 \x01(\tR\tserverUrl\x12\x1b\n" +
	"\troom_name\x18\x03 \x01(\tR\broomNameB.Z,github.com/AegisSec/veil-server/pkg/proto/v1b\x06proto3"

var (
	file_veil_v1_voice_proto_rawDescOnce sync.Once
	file_veil_v1_voice_proto_rawDescData []byte
)

func file_veil_v1_voice_proto_rawDescGZIP() []byte {
	file_veil_v1_voice_proto_rawDescOnce.Do(func() {
		file_veil_v1_voice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_veil_v1_voice_proto_rawDesc), len(file_veil_v1_voice_proto_rawDesc)))
	})
	return file_veil_v1_voice_proto_rawDescData
}

var file_veil_v1_voice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_veil_v1_voice_proto_goTypes = []any{
	(*VoiceTokenRequest)(nil), // 0: veil.v1.VoiceTokenRequest
	(*VoiceToken)(nil),        // 1: veil.v1.VoiceToken
}
var file_veil_v1_voice_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_veil_v1_voice_proto_init() }
func file_veil_v1_voice_proto_init() {
	if File_veil_v1_voice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_veil_v1_voice_proto_rawDesc), len(file_veil_v1_voice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_veil_v1_voice_proto_goTypes,
		DependencyIndexes: file_veil_v1_voice_proto_depIdxs,
		MessageInfos:      file_veil_v1_voice_proto_msgTypes,
	}.Build()
	File_veil_v1_voice_proto = out.File
	file_veil_v1_voice_proto_goTypes = nil
	file_veil_v1_voice_proto_depIdxs = nil
}
