// Package cryptokey centralizes validation of public cryptographic keys at
// network, storage and startup boundaries.
package cryptokey

import (
	"bytes"

	"filippo.io/edwards25519"
)

var ed25519OrderMinusOne = func() *edwards25519.Scalar {
	// l - 1, little-endian, where l is the prime order of the Ed25519 base
	// point. SetCanonicalBytes rejects an accidental non-canonical constant.
	encoded := []byte{
		0xec, 0xd3, 0xf5, 0x5c, 0x1a, 0x63, 0x12, 0x58,
		0xd6, 0x9c, 0xf7, 0xa2, 0xde, 0xf9, 0xde, 0x14,
		0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
		0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10,
	}
	scalar, err := new(edwards25519.Scalar).SetCanonicalBytes(encoded)
	if err != nil {
		panic("invalid Ed25519 subgroup constant")
	}
	return scalar
}()

// ValidEd25519PublicKey accepts only the canonical encoding of a non-identity
// point in the prime-order subgroup generated by the Ed25519 base point.
//
// crypto/ed25519 accepts some low-order verification edge cases for ecosystem
// compatibility. That is unsafe for an authoritative authentication key: a
// point without a prime-order secret can make a forged signature verify for a
// subset of messages. Requiring [l]P = identity rejects both pure small-order
// points and mixed prime-plus-torsion points without changing valid RFC 8032
// keys produced by standard clients.
func ValidEd25519PublicKey(key []byte) bool {
	if len(key) != 32 {
		return false
	}
	point, err := new(edwards25519.Point).SetBytes(key)
	if err != nil || !bytes.Equal(point.Bytes(), key) {
		return false
	}
	identity := edwards25519.NewIdentityPoint()
	if point.Equal(identity) == 1 {
		return false
	}

	// Scalars are represented modulo l, so compute l*P as (l-1)*P + P.
	// ScalarMult still performs the intended integer multiplication for any
	// Edwards point, including one with a torsion component.
	orderMultiple := new(edwards25519.Point).ScalarMult(ed25519OrderMinusOne, point)
	orderMultiple.Add(orderMultiple, point)
	return orderMultiple.Equal(identity) == 1
}
