import { StyleSheet } from 'react-native';
import { geometry, typography } from './appearance';
export const styles = StyleSheet.create({
  navigationSurface: { flex: 1 },
  home: { flex: 1, flexDirection: 'row', gap: 6 },
  dock: {
    width: 60,
    overflow: 'hidden',
    borderRadius: geometry.radius,
    borderWidth: geometry.borderWidth,
    paddingTop: 10,
    paddingBottom: 88,
    gap: 6,
  },
  dockDivider: { height: 1, marginHorizontal: 14, marginVertical: 3 },
  dockSpaces: { gap: 8, paddingBottom: 8 },
  island: {
    flex: 1,
    borderRadius: geometry.radius,
    borderWidth: geometry.borderWidth,
    overflow: 'hidden',
  },
  header: {
    minHeight: 60,
    paddingLeft: 14,
    paddingRight: 4,
    flexDirection: 'row',
    alignItems: 'center',
  },
  heading: {
    ...typography.heading,
    fontWeight: '600',
    letterSpacing: -0.4,
  },
  flex: { flex: 1, minWidth: 0 },
  searchBox: {
    marginHorizontal: 12,
    borderRadius: geometry.radius,
    flexDirection: 'row',
    alignItems: 'center',
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    minHeight: geometry.touchTarget,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  chatList: { paddingHorizontal: 10, paddingBottom: 96 },
  empty: { alignItems: 'center', paddingVertical: 28, gap: 12 },
  chatRow: {
    minHeight: 76,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 4,
    paddingVertical: 12,
    gap: 10,
    borderRadius: geometry.radius,
  },
  chatRowBody: { flex: 1, gap: 5, minWidth: 0 },
  rowTitle: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  chatName: { flex: 1, ...typography.name, fontWeight: '600' },
  time: {
    ...typography.micro,
    flexShrink: 0,
    minWidth: 38,
    textAlign: 'right',
  },
  previewText: { flex: 1, ...typography.caption },
  unreadBadge: {
    minWidth: 18,
    minHeight: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  unreadText: { fontSize: 10, lineHeight: 14, fontWeight: '700' },
  footer: {
    ...typography.micro,
    textAlign: 'center',
    paddingVertical: 20,
  },
  spaceHeader: {
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 16,
    gap: 4,
  },
  caption: { ...typography.caption },
  sectionLabel: {
    ...typography.micro,
    fontWeight: '600',
    letterSpacing: 1.2,
    marginTop: 24,
    marginBottom: 12,
  },
  channelRow: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 10,
    borderRadius: geometry.radius,
  },
  unreadDot: { width: 6, height: 6, borderRadius: 3 },
  dockItem: { height: 52, alignItems: 'center', justifyContent: 'center' },
  activePill: {
    position: 'absolute',
    left: 0,
    width: 3,
    height: 28,
    borderTopRightRadius: 3,
    borderBottomRightRadius: 3,
  },
  dockButton: {
    width: geometry.touchTarget,
    height: geometry.touchTarget,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pressed: { opacity: 0.7 },
  dockInitial: { fontSize: 18, fontWeight: '600' },
});
