import { StyleSheet } from 'react-native';
import { geometry, typography } from './appearance';
export const styles = StyleSheet.create({
  flex: { flex: 1, minWidth: 0 },
  pressed: { opacity: 0.7 },
  floating: {
    position: 'absolute',
    bottom: 8,
    left: 8,
    right: 8,
    minHeight: 72,
    borderRadius: geometry.radius,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 6,
    elevation: 18,
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
  },
  summary: {
    flex: 1,
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 8,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: geometry.radius,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  largeAvatar: { width: 64, height: 64, borderRadius: geometry.radius },
  initial: { fontSize: 20, fontWeight: '600' },
  statusDot: {
    position: 'absolute',
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#64748B',
    bottom: -2,
    right: -2,
    borderWidth: 2,
  },
  name: { fontSize: 15, fontWeight: '600', lineHeight: 23 },
  caption: { fontSize: 11, lineHeight: 18 },
  icon: {
    minWidth: geometry.touchTarget,
    minHeight: geometry.touchTarget,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalRoot: { flex: 1, justifyContent: 'flex-end' },
  panel: {
    flex: 1,
    borderTopLeftRadius: geometry.radius,
    borderTopRightRadius: geometry.radius,
    borderWidth: 1,
    overflow: 'hidden',
  },
  handleRow: { height: 18, alignItems: 'center', justifyContent: 'center' },
  handle: { width: 32, height: 4, borderRadius: 2 },
  panelHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 20,
    paddingRight: 8,
    minHeight: geometry.touchTarget,
  },
  title: { ...typography.heading, fontWeight: '600' },
  tabs: {
    flexDirection: 'row',
    gap: 20,
    paddingHorizontal: 20,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  tab: {
    minWidth: geometry.touchTarget,
    minHeight: geometry.touchTarget,
    borderBottomWidth: 2,
    justifyContent: 'center',
  },
  tabText: { fontSize: 14, lineHeight: 22, fontWeight: '600' },
  content: { padding: 18, paddingBottom: 30 },
  appearance: { flex: 1 },
  banner: {
    height: 100,
    borderRadius: geometry.radius,
    overflow: 'hidden',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  bannerStripe: {
    position: 'absolute',
    width: 220,
    height: 180,
    opacity: 0.12,
    right: -50,
    transform: [{ rotate: '-35deg' }],
  },
  bannerBrand: { letterSpacing: 5, fontWeight: '600', fontSize: 17 },
  identity: {
    marginTop: 16,
    gap: 14,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  profileName: { fontSize: 21, lineHeight: 28, fontWeight: '600' },
  body: { fontSize: 14, lineHeight: 23, marginVertical: 8 },
  input: {
    minHeight: geometry.touchTarget,
    padding: 14,
    borderRadius: geometry.radius,
    fontSize: 16,
    marginVertical: 6,
  },
  setting: {
    minHeight: 60,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: geometry.radius,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 10,
  },
  note: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    padding: 16,
    borderRadius: geometry.radius,
    marginTop: 12,
  },
  footnote: {
    fontSize: 10,
    lineHeight: 18,
    textAlign: 'center',
    paddingTop: 20,
  },
  switchRow: { flexDirection: 'row', gap: 12, alignItems: 'center' },
});
