-- Servers, Channels, Roles & Permissions
-- Builds on existing tables from 001_initial.sql:
--   servers, server_members, roles, channels

-- ─── Server: add description, member_count cache, deleted flag ─────────
ALTER TABLE servers
    ADD COLUMN IF NOT EXISTS description TEXT,
    ADD COLUMN IF NOT EXISTS deleted_at  TIMESTAMPTZ;

-- ─── Server members: nickname + roles ──────────────────────────────────
ALTER TABLE server_members
    ADD COLUMN IF NOT EXISTS nickname TEXT;

-- ─── Roles: ensure @everyone is identifiable, mentionable, hoist ───────
ALTER TABLE roles
    ADD COLUMN IF NOT EXISTS is_default  BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS hoist       BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS mentionable BOOLEAN DEFAULT FALSE;

CREATE UNIQUE INDEX IF NOT EXISTS idx_roles_default_per_server
    ON roles(server_id) WHERE is_default = TRUE;

-- Many-to-many: which roles a member has
CREATE TABLE IF NOT EXISTS member_roles (
    server_id UUID NOT NULL REFERENCES servers(id)        ON DELETE CASCADE,
    user_id   UUID NOT NULL REFERENCES users(id)          ON DELETE CASCADE,
    role_id   UUID NOT NULL REFERENCES roles(id)          ON DELETE CASCADE,
    assigned_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (server_id, user_id, role_id),
    FOREIGN KEY (server_id, user_id) REFERENCES server_members(server_id, user_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_member_roles_user ON member_roles(user_id);
CREATE INDEX IF NOT EXISTS idx_member_roles_role ON member_roles(role_id);

-- ─── Channels: topic already exists, add nsfw + slowmode + parent ─────
ALTER TABLE channels
    ADD COLUMN IF NOT EXISTS nsfw           BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS slowmode_secs  INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS created_at     TIMESTAMPTZ DEFAULT now();

-- Parent category support — category_id already in channels table
-- For text channels, conversation_id links to conversations table

-- ─── Channel permission overwrites (per-role / per-user) ──────────────
CREATE TABLE IF NOT EXISTS channel_overwrites (
    channel_id UUID NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    target_id  UUID NOT NULL,                  -- role_id OR user_id
    target_type SMALLINT NOT NULL,             -- 0=role, 1=user
    allow      BIGINT NOT NULL DEFAULT 0,      -- bitmask of allowed perms
    deny       BIGINT NOT NULL DEFAULT 0,      -- bitmask of denied perms
    PRIMARY KEY (channel_id, target_id, target_type)
);

-- ─── Invites ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS server_invites (
    code        TEXT PRIMARY KEY,                                          -- short URL-safe code
    server_id   UUID NOT NULL REFERENCES servers(id) ON DELETE CASCADE,
    created_by  UUID NOT NULL REFERENCES users(id),
    max_uses    INTEGER DEFAULT 0,                                         -- 0 = unlimited
    uses        INTEGER DEFAULT 0,
    expires_at  TIMESTAMPTZ,                                               -- NULL = never
    created_at  TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_invites_server ON server_invites(server_id);

-- ─── Audit log ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS server_audit (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    server_id   UUID NOT NULL REFERENCES servers(id) ON DELETE CASCADE,
    actor_id    UUID NOT NULL REFERENCES users(id),
    action      TEXT NOT NULL,                  -- e.g. "channel.create", "member.kick"
    target_id   UUID,
    metadata    JSONB,
    created_at  TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_audit_server ON server_audit(server_id, created_at DESC);

-- ─── Channel encryption (per-channel epoch keys, server-mediated) ─────
-- Hybrid model: server stores ONLY ciphertext + encrypted key envelopes.
-- Plaintext epoch keys are generated by clients and never seen by server.
-- Each channel has a chain of epochs; rotation happens on member leave/kick.
CREATE TABLE IF NOT EXISTS channel_epochs (
    channel_id    UUID NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    epoch         INTEGER NOT NULL,                          -- monotonic, starts at 0
    key_fp        BYTEA NOT NULL,                            -- public fingerprint of the key (for verification)
    created_by    UUID NOT NULL REFERENCES users(id),
    created_at    TIMESTAMPTZ DEFAULT now(),
    rotated_reason TEXT,                                     -- "init" | "member_left" | "member_kicked" | "manual"
    PRIMARY KEY (channel_id, epoch)
);

-- Per-recipient encrypted envelopes for a given epoch.
-- Distributed by clients with READ_MESSAGE_HISTORY permission via server.
-- Server sees only opaque encrypted_key bytes.
CREATE TABLE IF NOT EXISTS channel_key_envelopes (
    channel_id     UUID NOT NULL,
    epoch          INTEGER NOT NULL,
    recipient_id   UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    sender_id      UUID NOT NULL REFERENCES users(id),
    encrypted_key  BYTEA NOT NULL,                           -- epoch_key encrypted to recipient's identity_key
    created_at     TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (channel_id, epoch, recipient_id),
    FOREIGN KEY (channel_id, epoch) REFERENCES channel_epochs(channel_id, epoch) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_envelopes_recipient ON channel_key_envelopes(recipient_id, channel_id);

-- Track which epoch each message belongs to (for client-side key lookup).
ALTER TABLE messages
    ADD COLUMN IF NOT EXISTS channel_epoch INTEGER;
