/** Bundled product copy; identifiers, fingerprints and native values are never translated. */
const text: Record<string, string> = {
  'Unlock required': 'Нужно открыть аккаунт',
  'Veil locked this account when the app left the foreground. Reopen it explicitly to continue.': 'Veil заблокировал аккаунт при уходе в фон. Явно откройте его снова, чтобы продолжить.',
  'Local account locked': 'Локальный аккаунт заблокирован',
  'Your recovery material remains inside the encrypted native vault.': 'Материалы восстановления остаются в зашифрованном native-хранилище.',
  'Securing local account': 'Защищаем локальный аккаунт',
  'Waiting for the native encrypted session to settle.': 'Ожидаем завершения перехода защищённой native-сессии.',
  'Authenticating Veil Node': 'Подключаемся к Node',
  'Establishing the native encrypted transport and account binding.': 'Проверяем защищённое соединение и привязку аккаунта.',
  'Publishing device keys': 'Публикуем ключи устройства',
  'Preparing this device for authenticated encrypted conversations.': 'Готовим устройство к аутентифицированной зашифрованной переписке.',
  'Verifying conversations': 'Проверяем диалоги',
  'Loading the authenticated conversation directory into encrypted local storage.': 'Загружаем подтверждённый список диалогов в зашифрованное локальное хранилище.',
  'Restoring encrypted history': 'Восстанавливаем зашифрованную историю',
  'Validating and storing supported Direct messages before live chat can open.': 'Проверяем и сохраняем доступные сообщения Direct перед открытием переписки.',
  'Reconciling live messages': 'Согласуем новые сообщения',
  'History is synchronized. Veil is still waiting for safe live-message reconciliation.': 'История синхронизирована. Ожидаем безопасного согласования новых сообщений.',
  'Secure sync is not ready': 'Защищённая синхронизация не готова',
  'The account is authenticated, but native secure synchronization is still incomplete.': 'Аккаунт аутентифицирован, но защищённая native-синхронизация ещё не завершена.',
  'Connect to your Veil Node': 'Подключитесь к Node Veil',
  'Only the canonical server origin crosses this UI boundary. Authentication remains native.': 'Укажите канонический HTTPS-адрес сервера. Аутентификация выполняется в native-слое.',
  'Native secure session': 'Защищённая сессия', 'NODE ACCESS PASS': 'БИЛЕТ ДОСТУПА К NODE',
  'Review invitation': 'Проверьте приглашение',
  'This pass can register one account. Its bearer never enters JavaScript.': 'Билет разрешает регистрацию одного аккаунта. Его секретный токен не передаётся в JavaScript.',
  'Origin': 'Адрес Node', 'Reference': 'Локальная ссылка', 'Expires in': 'Осталось времени',
  'Opening securely...': 'Открываем защищённую сессию...', 'Use access pass': 'Использовать билет', 'Discard invitation': 'Отменить приглашение',
  'Have a Node invitation?': 'Есть приглашение на Node?',
  'Copy the HTTPS invitation link from your Node, then import it here to review the origin before registration.': 'Скопируйте HTTPS-ссылку приглашения и импортируйте её здесь. Перед регистрацией проверьте адрес Node.',
  'Importing securely...': 'Импортируем приглашение...', 'Import invitation from clipboard': 'Импортировать приглашение из буфера',
  'The link stays in the clipboard until you replace or clear it.': 'Ссылка останется в буфере, пока вы не замените или не очистите её.',
  'Unlocking...': 'Открываем аккаунт...', 'Unlock local account': 'Открыть локальный аккаунт',
  'Canonical Veil Node origin': 'Канонический HTTPS-адрес Node',
  'Connecting...': 'Подключаемся...', 'Connect securely': 'Подключиться защищённо',
  'Authenticated binding verified': 'Привязка аккаунта подтверждена', 'Binding verification unavailable': 'Проверка привязки недоступна',
  'Refreshing...': 'Обновляем состояние...', 'Refresh secure state': 'Проверить защищённое состояние',
  'Secure action in progress': 'Выполняется защищённое действие',
  'Messages stay hidden until the native session, exact account binding, and verified directory are all ready.': 'Переписка скрыта до готовности native-сессии, точной привязки аккаунта и проверенного списка диалогов.',
  'Veil is securing and locking the local account': 'Veil защищает и блокирует локальный аккаунт',
  'Veil is locked': 'Veil заблокирован',
  'Securing the local session before this screen can be shown again.': 'Защищаем локальную сессию перед повторным открытием интерфейса.',
};
export function runtimeCopy(key: string): string { return text[key] ?? key; }
